const e=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;};
const fields=(values)=>{const table=e('table');for(const [key,value] of Object.entries(values)){const row=e('tr');row.append(e('th',key),e('td',String(value)));table.append(row);}return table;};
export async function binaryExtraView(bytes,name,signal,onCleanup){
 const host=e('div');host.className='binary-extra';if(bytes.length>64*1024*1024)throw Error('Binary preview input exceeds 64 MiB');
 if(/\.hex$/i.test(name)){const pre=e('pre'),lines=[];for(let at=0;at<Math.min(bytes.length,65536);at+=16){const row=bytes.subarray(at,at+16);lines.push(at.toString(16).padStart(8,'0')+'  '+Array.from(row,b=>b.toString(16).padStart(2,'0').toUpperCase()).join(' ').padEnd(47)+'  '+Array.from(row,b=>b>=32&&b<127?String.fromCharCode(b):'.').join(''));}pre.textContent=lines.join('\n');host.append(e('h2','Binary bytes'),e('p','Raw byte/ASCII inspection, at most 65536 displayed bytes. This does not validate or load Intel HEX records.'),pre);return{host,typeId:'hex'};}
 const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),ascii=(at,size)=>new TextDecoder('ascii').decode(bytes.subarray(at,at+size));
 if(/\.vhd$/i.test(name)){
  if(bytes.length<512)throw Error('VHD footer is missing');const footer=bytes.length-512;if(ascii(footer,8)!=='conectix')throw Error('Invalid VHD footer cookie');
  const sum=(at,size,skip)=>{let total=0;for(let i=0;i<size;i++)if(i<skip||i>=skip+4)total=(total+bytes[at+i])>>>0;return (~total)>>>0;},u64=at=>{const value=view.getBigUint64(at,false);if(value>BigInt(Number.MAX_SAFE_INTEGER))throw Error('VHD offset/size exceeds safe range');return Number(value);};
  if(view.getUint32(footer+12)!==0x10000||view.getUint32(footer+64)!==sum(footer,512,64))throw Error('Invalid VHD footer version/checksum');
  const type=view.getUint32(footer+60),size=u64(footer+48),original=u64(footer+40);if(![2,3,4].includes(type)||!size||size%512)throw Error('Unsupported VHD type or invalid virtual size');
  const model={type:({2:'Fixed',3:'Dynamic',4:'Differencing'})[type],virtualBytes:size,originalBytes:original,creator:ascii(footer+28,4),created:new Date((view.getUint32(footer+24)+946684800)*1000).toISOString(),uuid:Array.from(bytes.subarray(footer+68,footer+84),b=>b.toString(16).padStart(2,'0')).join(''),checksum:'Valid'};
  if(type===2){if(view.getBigUint64(footer+16)!==0xffffffffffffffffn||size!==footer)throw Error('Invalid fixed VHD length/data offset');}
  else{
   const header=u64(footer+16);if(header%512||header<512||header+1024>footer||ascii(header,8)!=='cxsparse')throw Error('Invalid VHD dynamic header');if(view.getUint32(header+24)!==0x10000||view.getUint32(header+36)!==sum(header,1024,36))throw Error('Invalid VHD dynamic version/checksum');
   const table=u64(header+16),count=view.getUint32(header+28),block=view.getUint32(header+32);if(!block||block%512||(block&(block-1))||block>32*1024*1024||count>1000000||count<Math.ceil(size/block)||table%512||table<header+1024||table+count*4>footer)throw Error('Invalid VHD block table');
   let allocated=0;const ranges=[],bitmap=Math.ceil((block/512)/8/512)*512,tableEnd=table+Math.ceil(count*4/512)*512;
   for(let i=0;i<count;i++){const sector=view.getUint32(table+i*4);if(sector===0xffffffff)continue;const start=sector*512,end=start+bitmap+block;if(start<tableEnd||end>footer)throw Error('VHD allocated block exceeds file bounds');ranges.push([start,end]);allocated++;}ranges.sort((a,b)=>a[0]-b[0]);if(ranges.some((r,i)=>i>0&&r[0]<ranges[i-1][1]))throw Error('Overlapping VHD blocks');Object.assign(model,{blockBytes:block,blockTableEntries:count,allocatedBlocks:allocated,dynamicChecksum:'Valid'});
  }
  host.append(e('h2','VHD virtual disk'),fields(model),e('p','Native fixed/dynamic/differencing container metadata and block-table inspection only. No filesystem browsing, disk mounting, parent resolution or guest execution. 64 MiB file and 1,000,000 table entries.'));return{host,typeId:'vhd'};
 }
 if(bytes.length<82||view.getUint32(0,true)!==bytes.length||view.getUint16(34,true)!==0x504c)throw Error('Invalid EOT header size or magic');
 const version=view.getUint32(8,true),flags=view.getUint32(12,true),fontSize=view.getUint32(4,true),fsType=view.getUint16(32,true);if(![0x10000,0x20001,0x20002].includes(version)||!fontSize)throw Error('Unsupported EOT version or empty font');let at=80;
 const u16=()=>{if(at+2>bytes.length)throw Error('Truncated EOT header');const n=view.getUint16(at,true);at+=2;return n;},u32=()=>{if(at+4>bytes.length)throw Error('Truncated EOT header');const n=view.getUint32(at,true);at+=4;return n;},padding=()=>{if(u16()!==0)throw Error('Invalid EOT padding');},string=()=>{const n=u16();if(n%2||at+n>bytes.length)throw Error('Invalid EOT name length');const s=new TextDecoder('utf-16le',{fatal:true}).decode(bytes.subarray(at,at+n));at+=n;return s;};
 padding();const family=string();padding();const style=string();padding();const fontVersion=string();padding();const fullName=string();let roots='';if(version!==0x10000){padding();roots=string();}if(version===0x20002){const expected=u32(),rootEncoded=Uint8Array.from({length:roots.length*2},(_,i)=>(roots.charCodeAt(i>>1)>>(i%2*8))&255);if(((rootEncoded.reduce((sum,b)=>sum+b,0)^0x50475342)>>>0)!==expected)throw Error('Invalid EOT root checksum');u32();padding();const signature=u16();if(signature||u32()||u32())throw Error('EOT signatures/EUDC profiles are unsupported');}
 if(at+fontSize!==bytes.length)throw Error('EOT font bounds do not match header');host.append(e('h2','Embedded OpenType font'),fields({family,style,version:fontVersion,fullName,eotVersion:'0x'+version.toString(16),flags:'0x'+flags.toString(16),embeddingFlags:'0x'+fsType.toString(16),roots:roots||'Unrestricted',fontBytes:fontSize}));
 if(flags&4||flags&32||roots||(fsType&2)&&!(fsType&12)||fsType&512){host.append(e('p','Metadata only: compressed/EUDC data or embedding/root restrictions prevent this font specimen profile.'));return{host,typeId:'eot'};}
 const font=bytes.slice(at);if(flags&0x10000000)for(let i=0;i<font.length;i++)font[i]^=0x50;
 if(font.length<12)throw Error('Truncated EOT font data');const sfnt=new DataView(font.buffer),tables=sfnt.getUint16(4);if(![0x00010000,0x4f54544f].includes(sfnt.getUint32(0))||tables>256||12+tables*16>font.length)throw Error('Unsupported EOT SFNT font');
 for(let i=0;i<tables;i++){const p=12+i*16,offset=sfnt.getUint32(p+8),length=sfnt.getUint32(p+12);if(offset+length>font.length)throw Error('EOT SFNT table exceeds bounds');if(sfnt.getUint32(p)===0x4f532f32){if(length<10)throw Error('Invalid EOT OS/2 table');const embedding=sfnt.getUint16(offset+8);if((embedding&2)&&!(embedding&12)||embedding&512)throw Error('Embedded SFNT restricts this specimen profile');}}
 const fontFamily='eot-'+crypto.randomUUID(),face=new FontFace(fontFamily,font.buffer);await face.load();if(signal.aborted)throw new DOMException('Cancelled','AbortError');document.fonts.add(face);onCleanup(()=>document.fonts.delete(face));const specimen=e('div','Original42 · The quick brown fox jumps over the lazy dog.\nABCDEFGHIJKLMNOPQRSTUVWXYZ\nabcdefghijklmnopqrstuvwxyz 0123456789');specimen.className='eot-specimen';specimen.style.cssText='font-family:"'+fontFamily+'";font-size:32px;white-space:pre-wrap';host.append(e('p','Native temporary read-only SFNT specimen. Uncompressed EOT 1/2/2.2 and XOR data are supported; MicroType Express and EUDC are unsupported. Font is removed on replacement/disposal.'),specimen);return{host,typeId:'eot'};
}
