// Trusted shell around the pinned MIT jdeworks readers. Source previews retain
// the upstream opaque-origin iframe; input scripts remain disabled.
import {REGISTRY} from './core/registry-runtime.generated.js';
import {intakeFromBytes} from './core/intake.js';
import {descriptorsFor,previewStyle} from './core/settings-schema.js';
import {mountPreview} from './core/iframe.js';
const nativeCreate=URL.createObjectURL.bind(URL),nativeRevoke=URL.revokeObjectURL.bind(URL);
URL.createObjectURL=blob=>{const url=nativeCreate(blob);if(current)current.urls.add(url);return url;};
URL.revokeObjectURL=url=>{current?.urls.delete(url);nativeRevoke(url);};
const NativeWorker=Worker;window.Worker=class extends NativeWorker{constructor(...args){super(...args);const owner=current;if(owner)owner.cleanups.add(()=>this.terminate());}};
const LIMITS={asciiart:"Legacy CP437 text/ANSI SGR color preview; UTF-8 is accepted when explicitly marked with a BOM. Cursor positioning and terminal emulation are unsupported.",als:"Track/clip/plugin names and tempo only; audio, instruments and effects are not played.",prproj:"Project metadata and sequence/clip/media counts only; timeline visuals and media are not played.",hydrogen:"Native song/pattern or drumkit.xml metadata only; audio samples are not played. Drumkit TAR extraction validates paths and checksums.",shapefile:"Native shape headers, bounds and record-type counts only; geometry is not drawn and DBF/PRJ sidecars are not loaded.",wad:"Native lump directory and categories only; game maps, textures and audio are not rendered.",bsp:"Native header and entity properties only; map geometry and textures are not rendered.",dmp:"Windows minidump headers, stream directory and selected process/system fields; not a stack unwinder or full-memory dump reader.",geojson:"Topology/object and geometry summary only; TopoJSON arcs are not drawn.",kml:"Placemark and coordinate summary only; no map tiles or KML styling reconstruction.",proto:"Schema declaration preview; imports are not resolved and this is not a complete language validator.",thrift:"Schema declaration preview; imports are not resolved and this is not a complete language validator.",sdf:"Native connection-table summary and first molecule in 3D; up to five metadata records. No generated 2D chemical depiction.",cif:"Scalar metadata and atom coordinates; CIF2 list/dictionary/triple-quote syntax is unsupported.",pdb:"Protein Data Bank coordinates and metadata; Microsoft debug databases are unsupported.",mbtiles:'MBTiles archive metadata and zoom/tile counts; tiles are not decoded or mapped.',json5:'JSON5 parsed data tree. Comments are omitted; NaN and infinities display as their named strings.',msg:'Message headers and bodies only; attachment content and RTF bodies are not decoded.',lmms:'Project metadata and tracks only; audio, plugins and samples are not played.',mobi:'MOBI/PalmDOC book text only; DRM, HUFF/CDIC and KF8/AZW3 are unsupported.',f3d:'Saved thumbnail, manifest and archive contents only; geometry is not reconstructed.',sketch:'Saved preview and document structure; vector layout is not reconstructed.',procreate:'Saved thumbnail only; layers and full canvas are not reconstructed.',mat:'MAT v5 uncompressed variable metadata only; array values are not decoded.',exe:'Executable header inspection only; code is not executed or disassembled.',pyc:'Python bytecode header inspection only; code is not executed or disassembled.'};
const nonce=new URL(location.href).searchParams.get('nonce');const host=document.getElementById('host'),label=document.getElementById('label');let generation=0,current=null;
function release(){if(!current)return;current.controller.abort();for(const fn of [...current.cleanups].reverse())fn();for(const url of current.urls)nativeRevoke(url);current=null;host.replaceChildren();}
async function open(bytes,name,id){
 release();const seq=++generation,controller=new AbortController(),cleanups=new Set();current={controller,cleanups,urls:new Set()};const stale=()=>seq!==generation||controller.signal.aborted;
 if(/\.(ppt|pot|pps)$/i.test(name)){
  const {loadPptViewer}=await import('../ppt-viewer/index.mjs');if(stale())return;
  label.textContent='PowerPoint 97–2003 · Flyfish Viewer watermark';
  const runtime=await loadPptViewer({worker:true,cache:false});if(stale()){await runtime.close();return;}
  const view=await runtime.mount(host,bytes,{scale:0.75,virtualize:false,replace:false});
  if(stale()){await runtime.close();return;}
  const note=document.createElement('p');note.textContent='Static slide preview. Animations, macros and embedded applications are not executed. The upstream Flyfish Viewer watermark is retained.';host.prepend(note);
  parent.postMessage({readerBridge:true,nonce,id,model:{typeId:'ppt',summary:view.document.slideCount+' slides',slideCount:view.document.slideCount,width:view.document.width,height:view.document.height}},location.origin);return;
 }
 if(/\.(odt|odp|fodt|fodp|fods)$/i.test(name)){const {odfView}=await import('./odf.js');const view=await odfView(bytes,name,controller.signal);if(stale())return;label.textContent='OpenDocument';host.append(view);parent.postMessage({readerBridge:true,nonce,id,model:{typeId:'odf',summary:'OpenDocument native content'}},location.origin);return;}
 if(/\.(umd|mermaid|mmd)$/i.test(name)){const {extraView}=await import('./docextras.js');const view=await extraView(bytes,name,controller.signal);if(stale())return;const typeId=/\.umd$/i.test(name)?'umd':'mermaid';label.textContent=typeId;host.append(view);parent.postMessage({readerBridge:true,nonce,id,model:{typeId,summary:typeId}},location.origin);return;}
 if(/\.typst$/i.test(name)){const {typstView}=await import('./typst.js');const view=await typstView(bytes,controller.signal);if(stale())return;label.textContent='Typst';host.append(view);parent.postMessage({readerBridge:true,nonce,id,model:{typeId:'typst',summary:'Typst SVG pages'}},location.origin);return;}
 if(/\.(ans|nfo|diz)$/i.test(name)){const {decodeLegacyArt}=await import('./cp437.js');bytes=new TextEncoder().encode(decodeLegacyArt(bytes));}
 if(/\.svgz$/i.test(name)){const {projectXml}=await import('./project-xml.js');bytes=await projectXml(bytes,name,controller.signal);if(stale())return;}
 if(/\.kicad_(pro|prl|mod|sym|wks|dru)$/i.test(name)){const {kicadView}=await import('./kicad.js');const view=kicadView(bytes,name);if(stale())return;label.textContent='KiCad native structure';host.append(view);parent.postMessage({readerBridge:true,nonce,id,model:{typeId:'kicad',summary:'KiCad native structure'}},location.origin);return;}
 if(/\.(als|prproj|h2drumkit)$/i.test(name)){const {projectXml}=await import('./project-xml.js');bytes=await projectXml(bytes,name,controller.signal);if(stale())return;}
 if(/\.(sig|p7m|p7s|p7b|p7c|pkcs7|cms|cmsc|tsd|tst|tsq|tsr|asics|scs|asice|sce|ers|jws)$/i.test(name)){const {signatureView}=await import('./signature.js');const view=await signatureView(bytes,name,controller.signal);if(stale())return;label.textContent='Signature container';host.append(view.host);parent.postMessage({readerBridge:true,nonce,id,model:{typeId:'signature',summary:view.model.detectedFormat||view.model.kind||'JWS',inspection:view.model}},location.origin);return;}
 if(/\.bcf$/i.test(name)){const {bcfView}=await import('./bcf-view.js');const view=await bcfView(bytes,controller.signal);if(stale())return;label.textContent='BCF 2.2';host.append(view.host);parent.postMessage({readerBridge:true,nonce,id,model:{typeId:'bcf',label:'BCF 2.2',summary:view.count+' variants'}},location.origin);return;}
 if(/\.mmpz$/i.test(name)){const {decodeMmpz}=await import('./lmms.js');bytes=await decodeMmpz(bytes,controller.signal);if(stale())return;}
 if(/\.(url|webloc)$/i.test(name)){const {shortcutUrl}=await import('./shortcut.js');bytes=shortcutUrl(bytes,name);}
 if(/\.json5$/i.test(name)){const {parsedJson5}=await import('./json5-parser.js');bytes=new TextEncoder().encode(parsedJson5(new TextDecoder().decode(bytes)));}
 let binaryPlist=false;if(new TextDecoder().decode(bytes.slice(0,8))==='bplist00'){const {parseBinaryPlist}=await import('./bplist.js');bytes=new TextEncoder().encode(JSON.stringify(parseBinaryPlist(bytes)));binaryPlist=true;}
 const intake=intakeFromBytes(bytes,name);if(/\.(bson|cbor|msgpack|mpk|f3d|f3z|sketch|procreate|mat|dbf|exe|dll|dylib|macho|class|pyc|pyo|lnk|torrent|msg|mobi|azw)$/i.test(name))intake.isBinary=true;
 if(/\.bson$/i.test(name)&&(bytes.length<5||new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getInt32(0,true)!==bytes.length||bytes[bytes.length-1]!==0))throw Error('Invalid BSON document length or terminator');const ranked=REGISTRY.map(type=>({type,score:type.detect(intake)||0})).sort((a,b)=>b.score-a.score),best=ranked[0];if(!best||!best.score)throw Error('No upstream reader recognized '+name);const type=/\.webloc$/i.test(name)?REGISTRY.find(t=>t.id==='url'):binaryPlist?REGISTRY.find(t=>t.id==='json'):best.type;label.textContent=binaryPlist?'Binary Property List':type.label;const limitation=/\.gpkg$/i.test(name)?'GeoPackage tables and attributes; geometry BLOBs are not mapped.':binaryPlist?'Binary plist decoded data tree: dates, UID and large integers retain type tags; data shows up to 1024 bytes.':/\.json5$/i.test(name)?LIMITS.json5:LIMITS[type.id];if(limitation){const notice=document.createElement('p');notice.textContent=limitation;host.append(notice);}
 const settings=Object.fromEntries(descriptorsFor(type).map(d=>[d.key,d.default]));if(type.settingsUrl){const response=await fetch(type.settingsUrl,{signal:controller.signal});if(!response.ok)throw Error('Reader settings: HTTP '+response.status);const config=await response.json();for(const [key,value] of Object.entries(config.values||{}))if(Object.hasOwn(settings,key))settings[key]=value;}
 if(stale())return;
 const onCleanup=fn=>{if(stale()){fn();return()=>{};}cleanups.add(fn);return()=>cleanups.delete(fn);};let rendered;
 if(type.loadRenderer){const reader=await type.loadRenderer();if(stale())return;rendered=await reader.render(intake,{settings,signal:controller.signal,onCleanup,allowScripts:false,openIntake:inner=>open(inner.bytes,inner.filename,id),toast:message=>{if(!stale())label.textContent=String(message);}});}
 else if(type.capabilities?.rawView){const pre=document.createElement('pre');pre.textContent=intake.text;rendered={parentNode:pre};}
 else throw Error('This reader has no preview or text view');
 if(type.id==='gcode'&&/\.gc$/i.test(name)){const {gcodeSvg}=await import('./gcode.js');rendered.bodyHtml+=gcodeSvg(intake.text);}
 if(type.id==='sdf'&&rendered.parentNode){const heading=document.createElement('h3');heading.textContent=intake.text.split(/\r?\n/)[0];rendered.parentNode.prepend(heading);}
 if(type.id==='gff'){const {featureTable}=await import('./gff.js');rendered.bodyHtml+=featureTable(intake.text);}
 if(type.id==='lmms'&&/\.mmpz$/i.test(name))rendered.bodyHtml=rendered.bodyHtml.replace('Uncompressed (.mmp)','Qt qCompress (.mmpz)');
 if(type.id==='msg'){const {loadGlobal,vendor}=await import('./core/script-loader.js');const purify=await loadGlobal(vendor('dompurify/purify.min.js'),'DOMPurify');for(const frame of rendered.parentNode.querySelectorAll('iframe'))frame.srcdoc="<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; img-src data: blob:; style-src 'unsafe-inline'\">"+purify.sanitize(frame.srcdoc,{FORBID_TAGS:['script','iframe','object','embed','form','meta','link','base']});}
 for(const key of ['archiveCleanup','revoke','destroy'])if(rendered[key])onCleanup(rendered[key]);if(stale())return;
 if(rendered.parentNode)host.append(rendered.parentNode);else{
 // Opaque preview frames cannot fetch a blob owned by the trusted shell's
 // storage partition. Inline those image bytes before crossing that boundary.
 if(rendered.bodyHtml){const template=document.createElement('template');template.innerHTML=rendered.bodyHtml;for(const img of template.content.querySelectorAll('img[src^="blob:"]')){const response=await fetch(img.src,{signal:controller.signal});if(!response.ok)throw Error('Could not read preview image');const blob=await response.blob();img.src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});}rendered.bodyHtml=template.innerHTML;if(stale())return;}
const preview=mountPreview(host,{bodyHtml:rendered.bodyHtml,fullDoc:rendered.fullDoc,allowScripts:!!rendered.ranScripts,extraHead:rendered.extraHead||'',theme:'light',style:previewStyle(settings),readerPrefs:rendered.readerPrefs,onOpen:rendered.openEntry?async path=>{const entry=await rendered.openEntry(path);if(!stale())await open(entry.bytes,entry.filename||path,id);}:undefined});onCleanup(()=>preview.destroy());}
 parent.postMessage({readerBridge:true,nonce,id,model:{typeId:binaryPlist?'plist':type.id,label:binaryPlist?'Binary Property List':type.label,summary:binaryPlist?'Binary Property List':type.label}},location.origin);
}
window.addEventListener('message',event=>{if(event.source!==parent||event.origin!==location.origin||!event.data?.readerBridge||event.data.nonce!==nonce)return;const {bytes,name,id}=event.data;open(bytes,name,id).catch(error=>{if(error.name==='AbortError')return;label.textContent=error.message;parent.postMessage({readerBridge:true,nonce,id,error:error.message},location.origin);});});
window.addEventListener('pagehide',release);

parent.postMessage({readerBridge:true,nonce,ready:true},location.origin);
