const element=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
const table=(headers,rows)=>{const grid=element('table'),head=element('tr');for(const name of headers)head.append(element('th',name));grid.append(head);for(const values of rows){const row=element('tr');for(const value of values)row.append(element('td',String(value??'')));grid.append(row);}return grid;};
const text=bytes=>new TextDecoder('utf-8',{fatal:true}).decode(bytes);
function xmlPlist(bytes){const source=text(bytes).replace(/<!DOCTYPE plist PUBLIC "-\/\/Apple\/\/DTD PLIST 1\.0\/\/EN" "http:\/\/www\.apple\.com\/DTDs\/PropertyList-1\.0\.dtd">/,'');if(/<!DOCTYPE|<!ENTITY/i.test(source))throw Error('Unsupported plist external declaration');const doc=new DOMParser().parseFromString(source,'application/xml');if(doc.querySelector('parsererror')||doc.documentElement.tagName!=='plist'||doc.documentElement.children.length!==1)throw Error('Invalid archive XML plist');let dataSize=0,count=0;function value(node,depth=0){if(++count>100000||depth>128)throw Error('Archive plist object/depth limit');if(node.tagName==='dict'){const result=Object.create(null),nodes=[...node.children];if(nodes.length%2)throw Error('Invalid plist dictionary');for(let i=0;i<nodes.length;i+=2){if(nodes[i].tagName!=='key'||Object.hasOwn(result,nodes[i].textContent))throw Error('Invalid plist dictionary key');result[nodes[i].textContent]=value(nodes[i+1],depth+1);}return result;}if(node.tagName==='array')return [...node.children].map(n=>value(n,depth+1));if(node.tagName==='data'){const base64=node.textContent.replace(/\s/g,'');if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(base64))throw Error('Invalid plist data encoding');if(base64.length>Math.ceil(8*1024*1024/3)*4)throw Error('Archive resource exceeds 8 MiB');const decoded=atob(base64);dataSize+=decoded.length;if(dataSize>16*1024*1024)throw Error('Archive resources exceed 16 MiB');return Uint8Array.from(decoded,c=>c.charCodeAt(0));}if(['string','integer','real','date'].includes(node.tagName))return node.textContent;if(node.tagName==='true'||node.tagName==='false')return node.tagName==='true';throw Error('Unsupported archive plist value '+node.tagName);}return value(doc.documentElement.firstElementChild);}
export async function browserTextView(bytes,name){
 if(bytes.length>32*1024*1024)throw Error('Text/archive input exceeds 32 MiB');const host=element('div');host.className='browser-text';let html,typeId;
 if(/\.webarchive$/i.test(name)){
  const binary=text(bytes.subarray(0,8))==='bplist00',archive=binary?(await import('./bplist.js')).parseBinaryPlist(bytes,{rawData:true}):xmlPlist(bytes),main=archive.WebMainResource;
  if(!main||!(main.WebResourceData instanceof Uint8Array)||typeof main.WebResourceMIMEType!=='string')throw Error('Missing native WebMainResource data/MIME type');
  host.append(element('h2','Saved web archive'),element('p',main.WebResourceURL||''));const resources=archive.WebSubresources||[];if(!Array.isArray(resources)||resources.length>1000)throw Error('Invalid archive subresource list');host.append(table(['Resource URL','MIME type','Bytes'],[main,...resources].map(r=>[r.WebResourceURL,r.WebResourceMIMEType,r.WebResourceData instanceof Uint8Array?r.WebResourceData.length:'Unavailable'])));
  host.append(element('p','Main HTML/text only; scripts, styles, subframes, images and resource loading are unavailable. Native binary or XML plist; 8 MiB per resource and 16 MiB combined.'));
  if(main.WebResourceTextEncodingName&&!/^(utf-8|utf8)$/i.test(main.WebResourceTextEncodingName))throw Error('Only explicit UTF-8 archived pages are supported');const source=text(main.WebResourceData);
  if(main.WebResourceMIMEType==='text/plain')html=element('pre',source).outerHTML;else if(['text/html','application/xhtml+xml'].includes(main.WebResourceMIMEType))html=source;else throw Error('Archive main resource is not HTML or plain text');typeId='webarchive';
 }else if(/\.xhtml$/i.test(name)){
  if(bytes.length>4*1024*1024)throw Error('XHTML exceeds 4 MiB');html=text(bytes);if(/<!ENTITY/i.test(html))throw Error('XHTML entities are unsupported');const doc=new DOMParser().parseFromString(html,'application/xhtml+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='html'||doc.documentElement.namespaceURI!=='http://www.w3.org/1999/xhtml')throw Error('Invalid native XHTML document');typeId='xhtml';host.append(element('p','Inert XHTML content preview; scripts, styles, frames, images and external resources are unavailable.'));
 }else if(/\.lrc$/i.test(name)){
  const source=text(bytes);if(source.length>2*1024*1024)throw Error('LRC source exceeds 2 MiB');const rows=[],metadata=[];let offset=0;for(const line of source.split(/\r?\n/)){const meta=line.match(/^\[([a-z]+):([^\]]*)\]\s*$/i);if(meta){if(meta[1].toLowerCase()==='offset'){offset=Number(meta[2]);if(!Number.isSafeInteger(offset)||Math.abs(offset)>86400000)throw Error('Invalid LRC offset');}metadata.push([meta[1],meta[2]]);continue;}const stamps=[...line.matchAll(/\[(\d{1,4}):(\d{2})(?:[.:](\d{1,3}))?\]/g)];if(!stamps.length){if(line.trim())throw Error('Untimed LRC lyric line');continue;}const lyric=line.replace(/\[\d{1,4}:\d{2}(?:[.:]\d{1,3})?\]/g,'');if(/<\d+:\d+/.test(lyric))throw Error('Enhanced word-timed LRC is unsupported');for(const stamp of stamps){const seconds=Number(stamp[2]);if(seconds>=60)throw Error('Invalid LRC seconds');rows.push([Number(stamp[1])*60000+seconds*1000+Number((stamp[3]||'').padEnd(3,'0')),lyric]);if(rows.length>10000)throw Error('LRC exceeds 10000 cues');}}
  if(!rows.length)throw Error('No timed LRC cues');rows.sort((a,b)=>a[0]-b[0]);host.append(element('h2','Timed lyrics'),table(['Metadata','Value'],metadata),table(['Time (milliseconds)','Lyric'],rows.map(([time,lyric])=>[time+offset,lyric])),element('p','Native line timing and millisecond offsets; no audio playback or enhanced word timing.'));return {host,typeId:'lrc'};
 }else if(/\.m3u8$/i.test(name)){
  const lines=text(bytes).replace(/^\uFEFF/,'').split(/\r?\n/);if(lines.shift()?.trim()!=='#EXTM3U')throw Error('Expected native M3U8 header');if(lines.join('\n').length>2*1024*1024)throw Error('Playlist source exceeds 2 MiB');const rows=[],tags=[];let duration='',title='',variant='';for(const raw of lines){const line=raw.trim();if(tags.length>10000)throw Error('Playlist exceeds 10000 tags');if(!line)continue;if(line.startsWith('#')){if(line.startsWith('#EXTINF:')){const match=line.match(/^#EXTINF:([+-]?(?:\d+(?:\.\d*)?|\.\d+)),(.*)$/);if(!match||!Number.isFinite(Number(match[1]))||Number(match[1])< -1)throw Error('Invalid playlist duration');duration=match[1];title=match[2];}else if(line.startsWith('#EXT-X-STREAM-INF:'))variant=line.slice(18);else tags.push([line.split(':')[0],line.includes(':')?line.slice(line.indexOf(':')+1):'']);continue;}rows.push([line,duration,title,variant]);duration=title=variant='';if(rows.length>10000)throw Error('Playlist exceeds 10000 items');}if(duration||variant)throw Error('Playlist metadata has no following URI');host.append(element('h2','M3U8 playlist'),table(['Tag','Value'],tags),table(['URI','Duration (seconds)','Title','Variant attributes'],rows),element('p','Native UTF-8 playlist/HLS tags and segment/variant URI inspection. Entries, keys and nested playlists are not fetched; no playback.'));return {host,typeId:'m3u8'};
 }else throw Error('Unsupported browser/text reader');
 if(html.length>4*1024*1024)throw Error('HTML preview exceeds 4 MiB');
 const {loadGlobal,vendor}=await import('./core/script-loader.js');const purify=await loadGlobal(vendor('dompurify/purify.min.js'),'DOMPurify');html=purify.sanitize(html,{FORBID_TAGS:['script','style','iframe','object','embed','form','meta','link','base','img','image','audio','video','source','svg','math'],FORBID_ATTR:['style','srcdoc']});const template=document.createElement('template');template.innerHTML=html;for(const a of template.content.querySelectorAll('a'))a.replaceWith(...a.childNodes);return{host,typeId,html:template.innerHTML};
}
