const NS='http://www.w3.org/2000/svg';
function svgElement(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,String(v));if(text!==undefined)n.textContent=text;return n;}
function numeric(value,defaultValue=0){const n=Number(value??defaultValue);if(!Number.isFinite(n)||Math.abs(n)>1000000)throw Error('Invalid diagram coordinate');return n;}
function color(value,fallback){return typeof value==='string'&&(/^(#[\da-f]{3,8}|transparent|none|black|white|red|blue|green|yellow|orange|purple|gray|grey)$/i.test(value))?value:fallback;}
function xml(source){if(source.length>4*1024*1024||/<!\s*(DOCTYPE|ENTITY)/i.test(source))throw Error('Diagram XML exceeds limits or declares entities');const doc=new DOMParser().parseFromString(source,'application/xml');if(doc.querySelector('parsererror'))throw Error('Invalid diagram XML');const nodes=doc.querySelectorAll('*');if(nodes.length>30000)throw Error('Diagram XML exceeds 30000 elements');for(const node of nodes){let d=0;for(let p=node;p;p=p.parentElement)if(++d>64)throw Error('Diagram XML exceeds 64 levels');}return doc;}
async function worker(kind,source,signal){const w=new Worker(new URL('../diagram-viewer/worker.js',import.meta.url),{type:'module'});return new Promise((resolve,reject)=>{let timer;const done=(error,data)=>{clearTimeout(timer);signal.removeEventListener('abort',abort);w.terminate();error?reject(error):resolve(data);},abort=()=>done(new DOMException('Cancelled','AbortError'));signal.addEventListener('abort',abort,{once:true});if(signal.aborted)return abort();timer=setTimeout(()=>done(Error('Diagram parser exceeded 20 seconds')),20000);w.onmessage=e=>done(e.data.error?Error(e.data.error):null,e.data);w.onerror=e=>done(Error(e.message));w.postMessage({kind,source});});}
function scene(shapes){if(!shapes.length||shapes.length>5000)throw Error('Diagram requires 1–5000 supported shapes');const svg=svgElement('svg',{role:'img',class:'native-diagram'}),bounds=[];let totalPoints=0;
 for(const s of shapes){const x=numeric(s.x),y=numeric(s.y),w=numeric(s.w),h=numeric(s.h),angle=numeric(s.angle);if(w<0||h<0)throw Error('Negative diagram dimensions');const g=svgElement('g',{transform:`translate(${x} ${y}) rotate(${angle*180/Math.PI} ${w/2} ${h/2})`}),style={fill:color(s.fill,'none'),stroke:color(s.stroke,'#333'),'stroke-width':Math.max(.1,Math.min(20,numeric(s.strokeWidth,2)))};
  if(s.type==='rectangle')g.append(svgElement('rect',{...style,width:w,height:h}));else if(s.type==='ellipse')g.append(svgElement('ellipse',{...style,cx:w/2,cy:h/2,rx:w/2,ry:h/2}));else if(s.type==='diamond')g.append(svgElement('polygon',{...style,points:`${w/2},0 ${w},${h/2} ${w/2},${h} 0,${h/2}`}));else if(['line','arrow','freedraw'].includes(s.type)){if(!Array.isArray(s.points)||s.points.length<2||s.points.length>10000)throw Error('Invalid diagram point list');if((totalPoints+=s.points.length)>50000)throw Error('Diagram exceeds 50000 points');const points=s.points.map(p=>[numeric(p[0]),numeric(p[1])]);g.append(svgElement('polyline',{...style,fill:'none',points:points.map(p=>p.join(',')).join(' ')}));for(const p of points)bounds.push([x+p[0],y+p[1]]);if(s.type==='arrow'){const a=points.at(-2),b=points.at(-1),v=Math.atan2(b[1]-a[1],b[0]-a[0]);g.append(svgElement('path',{d:`M ${b[0]-10*Math.cos(v-.5)} ${b[1]-10*Math.sin(v-.5)} L ${b[0]} ${b[1]} L ${b[0]-10*Math.cos(v+.5)} ${b[1]-10*Math.sin(v+.5)}`,stroke:style.stroke,fill:'none'}));}}
  else if(s.type!=='text')throw Error('Unsupported diagram shape '+s.type);
  if(s.text){const label=svgElement('text',{x:s.type==='text'?0:w/2,y:s.type==='text'?20:h/2,'text-anchor':s.type==='text'?'start':'middle',fill:color(s.textColor,'#222'),'font-size':Math.min(100,Math.max(8,numeric(s.fontSize,16)))});String(s.text).split('\n').slice(0,100).forEach((line,i)=>label.append(svgElement('tspan',{x:s.type==='text'?0:w/2,dy:i?20:0},line)));g.append(label);}svg.append(g);const radius=Math.hypot(w,h);bounds.push([x-radius,y-radius],[x+radius,y+radius]);
 }
 const xs=bounds.map(p=>p[0]),ys=bounds.map(p=>p[1]),minX=Math.min(...xs)-20,minY=Math.min(...ys)-20,width=Math.max(...xs)-minX+20,height=Math.max(...ys)-minY+20;svg.setAttribute('viewBox',`${minX} ${minY} ${Math.max(1,width)} ${Math.max(1,height)}`);svg.style.cssText='width:100%;height:550px;background:white';return svg;}
function jsonScene(source,kind){const data=JSON.parse(source),shapes=[];let ignored=0;
 if(kind==='excalidraw'){if(data.type!=='excalidraw'||data.version!==2||!Array.isArray(data.elements)||data.elements.length>5000)throw Error('Expected an Excalidraw version-2 scene');for(const e of data.elements){if(e.isDeleted)continue;if(!['rectangle','ellipse','diamond','text','line','arrow','freedraw'].includes(e.type)){ignored++;continue;}shapes.push({type:e.type,x:e.x,y:e.y,w:e.width,h:e.height,angle:e.angle,fill:e.backgroundColor,stroke:e.strokeColor,strokeWidth:e.strokeWidth,text:e.text,fontSize:e.fontSize,textColor:e.strokeColor,points:e.points});}}
 else{if(data.tldrawFileFormatVersion!==1||!data.schema||!Array.isArray(data.records)||data.records.length>10000)throw Error('Expected a native tldraw file version 1');const pages=new Set(data.records.filter(r=>r.typeName==='page').map(r=>r.id));if(!pages.size)throw Error('tldraw page records are missing');const palette={black:'#1d1d1d',grey:'#9fa8b2',red:'#e03131',blue:'#4263eb',green:'#099268',yellow:'#f59f00',orange:'#f76707',violet:'#7048e8',white:'#ffffff'};for(const r of data.records){if(r.typeName!=='shape')continue;if(!pages.has(r.parentId)){ignored++;continue;}const p=r.props;if(!p||!['geo','text','line'].includes(r.type)){ignored++;continue;}const c=palette[p.color]||'#1d1d1d';let text=p.text;if(!text&&p.richText){let nodes=0;const visit=(n,d=0)=>{if(++nodes>10000||d>32)throw Error('tldraw rich text exceeds limits');return n.type==='text'?String(n.text||''):(n.content||[]).map(c=>visit(c,d+1)).join(n.type==='doc'?'\n':'');};text=visit(p.richText);}const type=r.type==='geo'?({rectangle:'rectangle',ellipse:'ellipse',diamond:'diamond'}[p.geo]):r.type;if(!type){ignored++;continue;}const points=type==='line'?Object.values(p.points||{}).sort((a,b)=>String(a.index).localeCompare(String(b.index))).map(p=>[p.x,p.y]):undefined;shapes.push({type,x:r.x,y:r.y,w:p.w??0,h:p.h??0,angle:r.rotation,fill:p.fill==='solid'?c:'none',stroke:c,text,textColor:c,points});}}
 return{shapes,ignored};}
async function drawio(source,signal){const doc=xml(source),models=[];let expandedBytes=source.length,totalShapes=0;if(doc.documentElement.localName==='mxGraphModel')models.push(doc.documentElement);else if(doc.documentElement.localName==='mxfile'){const pages=[...doc.documentElement.children].filter(n=>n.localName==='diagram');if(!pages.length||pages.length>20)throw Error('Draw.io requires 1–20 pages');for(const p of pages){let model=p.querySelector('mxGraphModel');if(!model){const inflated=await worker('compressed',p.textContent.trim(),signal);expandedBytes+=inflated.xml.length;if(expandedBytes>8*1024*1024)throw Error('Draw.io cumulative expansion exceeds 8 MiB');model=xml(inflated.xml).documentElement;}if(model.localName!=='mxGraphModel')throw Error('Draw.io page lacks mxGraphModel');models.push(model);}}else throw Error('Expected native mxfile or mxGraphModel');
 const views=[];for(const model of models){const cells=[...model.querySelectorAll('mxCell')];if(cells.length>5000)throw Error('Draw.io exceeds 5000 cells');const map=new Map();for(const c of cells){const id=c.getAttribute('id');if(!id||map.has(id))throw Error('Missing or duplicate Draw.io cell ID');map.set(id,c);}const positions=new Map();const position=(c,seen=new Set())=>{const id=c.getAttribute('id');if(positions.has(id))return positions.get(id);if(seen.has(id)||seen.size>64)throw Error('Cyclic Draw.io parent graph');seen.add(id);const geo=c.querySelector(':scope > mxGeometry'),parent=map.get(c.getAttribute('parent'));const a=parent?position(parent,seen):[0,0];if(geo?.getAttribute('relative')==='1'&&c.getAttribute('vertex')==='1')throw Error('Relative Draw.io vertices are unsupported');const p=[a[0]+numeric(geo?.getAttribute('x')),a[1]+numeric(geo?.getAttribute('y'))];positions.set(id,p);return p;};const shapes=[];let ignored=0;for(const c of cells){if(c.getAttribute('vertex')!=='1'&&c.getAttribute('edge')!=='1')continue;const geo=c.querySelector(':scope > mxGeometry');if(!geo)throw Error('Draw.io cell lacks geometry');const style=Object.fromEntries((c.getAttribute('style')||'').split(';').filter(x=>x.includes('=')).map(x=>x.split('=')));const [x,y]=position(c),w=numeric(geo.getAttribute('width')),h=numeric(geo.getAttribute('height'));let type=style.shape||((c.getAttribute('style')||'').split(';').includes('ellipse')?'ellipse':'rectangle'),points;
 if(c.getAttribute('edge')==='1'){type='line';const explicit=[...geo.querySelectorAll('mxPoint')].filter(p=>p.getAttribute('as')==='sourcePoint'||p.getAttribute('as')==='targetPoint');const endpoint=(attr,as)=>{const target=map.get(c.getAttribute(attr));if(target){const p=position(target),g=target.querySelector(':scope > mxGeometry');return[p[0]+numeric(g?.getAttribute('width'))/2-x,p[1]+numeric(g?.getAttribute('height'))/2-y];}const point=explicit.find(p=>p.getAttribute('as')===as);if(!point)throw Error('Draw.io edge endpoint missing');return[numeric(point.getAttribute('x')),numeric(point.getAttribute('y'))];};points=[endpoint('source','sourcePoint'),...[...geo.querySelectorAll('Array[as="points"] > mxPoint')].map(p=>[numeric(p.getAttribute('x')),numeric(p.getAttribute('y'))]),endpoint('target','targetPoint')];if(style.endArrow&&style.endArrow!=='none')type='arrow';}
 if(!['rectangle','ellipse','rhombus','line','arrow'].includes(type)){ignored++;continue;}shapes.push({type:type==='rhombus'?'diamond':type,x,y,w,h,angle:numeric(style.rotation)*Math.PI/180,fill:style.fillColor,stroke:style.strokeColor,text:c.getAttribute('value'),textColor:style.fontColor,fontSize:style.fontSize,points});}totalShapes+=shapes.length;if(totalShapes>5000)throw Error('Draw.io exceeds 5000 total shapes');views.push({shapes,ignored});}return views;}
function plantScene(diagram){const nodes=diagram.elements.filter(e=>typeof e.name==='string'),links=diagram.elements.filter(e=>typeof e.left==='string'&&typeof e.right==='string');if(!nodes.length)throw Error('No recognized PlantUML node declarations');const map=new Map(),shapes=nodes.map((n,i)=>{const x=(i%3)*280,y=Math.floor(i/3)*220;map.set(n.name,[x+110,y+75]);return{type:'rectangle',x,y,w:220,h:150,text:[n.title||n.name,...(n.members||[]).slice(0,5).map(m=>(m.accessor||'')+m.name+(m.type?': '+m.type:''))].join('\n'),fill:'#ffffff',stroke:'#333'};});for(const l of links){if(l.hidden)continue;const a=map.get(l.left),b=map.get(l.right);if(a&&b)shapes.push({type:l.rightArrowHead?'arrow':'line',x:0,y:0,w:0,h:0,points:[a,b],stroke:'#555'});}return shapes;}
export async function diagramView(bytes,name,signal){if(bytes.length>2*1024*1024)throw Error('Diagram exceeds 2 MiB');const source=new TextDecoder('utf-8',{fatal:true}).decode(bytes),kind=name.split('.').at(-1).toLowerCase(),host=document.createElement('div');host.className='diagram-native';const note=document.createElement('p');note.textContent='Native static diagram preview. Basic geometry and literal text; unsupported shapes are counted. Fonts, images, rich HTML, editing, rough strokes and automatic routing are unavailable. 2 MiB source, 5000 shapes.';host.append(note);
 if(['plantuml','puml'].includes(kind)){const {diagram}=await worker('plantuml',source,signal);note.textContent='Native PlantUML PEG parser: class/component/use-case AST and declared node relationships. Simple grid layout, not the PlantUML rendering engine. The parser can ignore unsupported statements; preprocessor directives are rejected. 64 KiB, 250 elements, 20 seconds.';host.append(scene(plantScene(diagram)));const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='Native parsed elements';pre.textContent=JSON.stringify(diagram,null,2);details.append(summary,pre);host.append(details);}
 else{const pages=['drawio','dio'].includes(kind)?await drawio(source,signal):[jsonScene(source,kind)];for(const [i,p]of pages.entries()){const title=document.createElement('h2');title.textContent=`Page ${i+1} · ${p.shapes.length} native shapes · ${p.ignored} unsupported`;host.append(title,scene(p.shapes));}}if(signal.aborted)throw new DOMException('Cancelled','AbortError');return host;}
