export async function extraView(bytes,name,signal){
 const host=document.createElement('div');host.className='doc-extras';
 if(/\.umd$/i.test(name)){
  const worker=new Worker(new URL('../docextras-viewer/umd-worker.js',import.meta.url),{type:'module'});
  const book=await new Promise((resolve,reject)=>{let timer;const finish=(error,value)=>{clearTimeout(timer);signal.removeEventListener('abort',abort);worker.terminate();error?reject(error):resolve(value);},abort=()=>finish(new DOMException('Cancelled','AbortError'));signal.addEventListener('abort',abort,{once:true});if(signal.aborted){abort();return;}timer=setTimeout(()=>finish(Error('UMD reader exceeded 20 seconds')),20000);worker.onmessage=e=>finish(e.data.error?Error(e.data.error):null,e.data.book);worker.onerror=e=>finish(Error(e.message));worker.postMessage(bytes.slice().buffer);});
  const title=document.createElement('h1');title.textContent=book.title;const details=document.createElement('p');details.textContent=[book.author,book.publisher,book.publishedAt].filter(Boolean).join(' · ');const note=document.createElement('p');note.textContent='Native UMD text chapters. Comics and mixed-image books are unsupported. Zlib text profile; 2 MiB input, 8 MiB expanded text, 20 seconds.';host.append(title,details,note);for(const chapter of book.chapters){const section=document.createElement('section'),heading=document.createElement('h2'),body=document.createElement('pre');heading.textContent=chapter.title;body.textContent=chapter.content;body.style.whiteSpace='pre-wrap';section.append(heading,body);host.append(section);}return host;
 }
 const source=new TextDecoder('utf-8',{fatal:true}).decode(bytes);const {renderDiagram}=await import('../docextras-viewer/mermaid.js');const svg=await renderDiagram(source);if(signal.aborted)throw new DOMException('Cancelled','AbortError');const {sanitizeSvg}=await import('./types/image/svg-sanitize.js');const note=document.createElement('p');note.textContent='Native local Mermaid diagram rendering. External resources, configuration directives and clickable callbacks are unavailable. 64 KiB source, 250 edges, 8 MiB SVG.';const drawing=document.createElement('div');drawing.className='mermaid-diagram';drawing.innerHTML=sanitizeSvg(svg);for(const anchor of drawing.querySelectorAll('a'))anchor.replaceWith(...anchor.childNodes);host.append(note,drawing);return host;
}
