const NS={office:'urn:oasis:names:tc:opendocument:xmlns:office:1.0',text:'urn:oasis:names:tc:opendocument:xmlns:text:1.0',table:'urn:oasis:names:tc:opendocument:xmlns:table:1.0',draw:'urn:oasis:names:tc:opendocument:xmlns:drawing:1.0',style:'urn:oasis:names:tc:opendocument:xmlns:style:1.0',fo:'urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0',manifest:'urn:oasis:names:tc:opendocument:xmlns:manifest:1.0'};
const attr=(node,ns,key)=>node.getAttributeNS(NS[ns],key);
function xmlDocument(bytes){if(bytes.length>4*1024*1024)throw Error('ODF XML exceeds 4 MiB');const xml=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('ODF external declarations are unsupported');const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw Error('Invalid ODF XML');if(doc.querySelectorAll('*').length>75000)throw Error('ODF exceeds 75000 XML elements');return doc;}
export async function odfView(bytes,name,signal){
 const kind=name.toLowerCase().split('.').pop();let manifest;
 if(kind==='odt'||kind==='odp'){
  const worker=new Worker(new URL('../docextras-viewer/odf-worker.js',import.meta.url),{type:'module'});
  const data=await new Promise((resolve,reject)=>{let timer;const finish=(error,value)=>{clearTimeout(timer);signal.removeEventListener('abort',abort);worker.terminate();error?reject(error):resolve(value);},abort=()=>finish(new DOMException('Cancelled','AbortError'));signal.addEventListener('abort',abort,{once:true});if(signal.aborted){abort();return;}timer=setTimeout(()=>finish(Error('ODF package reader exceeded 20 seconds')),20000);worker.onmessage=e=>finish(e.data.error?Error(e.data.error):null,e.data);worker.onerror=e=>finish(Error(e.message));worker.postMessage({bytes:bytes.slice().buffer,kind});});bytes=data.xml;manifest=xmlDocument(data.manifest);if(manifest.documentElement.namespaceURI!==NS.manifest||manifest.documentElement.localName!=='manifest')throw Error('Invalid ODF manifest');if(manifest.getElementsByTagNameNS(NS.manifest,'encryption-data').length)throw Error('Encrypted ODF packages are unsupported');
 }
 const doc=xmlDocument(bytes),root=doc.documentElement,family=kind==='fods'?'spreadsheet':kind==='odp'||kind==='fodp'?'presentation':'text';
 if(root.namespaceURI!==NS.office||root.localName!==(kind.startsWith('fod')?'document':'document-content'))throw Error('Invalid native ODF document root');
 if(kind.startsWith('fod')&&attr(root,'office','mimetype')!=='application/vnd.oasis.opendocument.'+(family==='text'?'text':family))throw Error('Flat ODF mimetype does not match extension');
 const body=[...root.children].find(n=>n.namespaceURI===NS.office&&n.localName==='body'),content=body&&[...body.children].find(n=>n.namespaceURI===NS.office&&n.localName===family);if(!content)throw Error('Missing native ODF '+family+' body');
 const host=document.createElement('div');host.className='odf-document';const note=document.createElement('p');note.textContent='Native OpenDocument text, tables and slide text preview. Basic bold/italic styles only; page layout, drawings, images, notes, formula evaluation and macros are unsupported. 4 MiB XML, 75,000 elements, 100 slides, 512 rows × 128 columns per table. Package ZIP validation and 32 MiB expanded limits apply.';host.append(note);
 const styles=new Map();for(const style of doc.getElementsByTagNameNS(NS.style,'style')){const props=[...style.children].find(n=>n.namespaceURI===NS.style&&n.localName==='text-properties');if(props)styles.set(attr(style,'style','name'),{bold:attr(props,'fo','font-weight')==='bold',italic:attr(props,'fo','font-style')==='italic'});}
 let chars=0,cells=0,paragraphs=0;
 const inline=(source,target,depth=0)=>{if(depth>64)throw Error('ODF text nesting exceeds 64');for(const node of source.childNodes){if(node.nodeType===3){chars+=node.textContent.length;if(chars>2*1024*1024)throw Error('ODF visible text exceeds 2 MiB');target.append(document.createTextNode(node.textContent));}else if(node.nodeType===1){if(node.namespaceURI===NS.text&&node.localName==='s'){const count=Number(attr(node,'text','c')||1);if(!Number.isInteger(count)||count<1||count>1000)throw Error('Invalid ODF space count');target.append(document.createTextNode(' '.repeat(count)));}else if(node.namespaceURI===NS.text&&node.localName==='tab')target.append(document.createTextNode('\t'));else if(node.namespaceURI===NS.text&&node.localName==='line-break')target.append(document.createElement('br'));else{const span=document.createElement('span'),style=styles.get(attr(node,'text','style-name'));if(style?.bold)span.style.fontWeight='bold';if(style?.italic)span.style.fontStyle='italic';inline(node,span,depth+1);target.append(span);}}}};
 const paragraph=(node,target)=>{if(++paragraphs>10000)throw Error('ODF exceeds 10000 visible paragraphs');const level=Math.max(1,Math.min(6,Number(attr(node,'text','outline-level'))||1)),p=document.createElement(node.localName==='h'?'h'+level:'p');inline(node,p);const style=styles.get(attr(node,'text','style-name'));if(style?.bold)p.style.fontWeight='bold';if(style?.italic)p.style.fontStyle='italic';target.append(p);};
 const repeat=(node,key)=>{const n=Number(attr(node,'table',key)||1);if(!Number.isSafeInteger(n)||n<1)throw Error('Invalid ODF repetition');return n;};
 const table=(node,target)=>{if(node.getElementsByTagNameNS(NS.table,'table').length)throw Error('Nested ODF tables are unsupported');const heading=document.createElement('h3');heading.textContent=attr(node,'table','name')||'Table';const grid=document.createElement('table');grid.className='odf-table';let rowCount=0,truncated=false;for(const row of node.getElementsByTagNameNS(NS.table,'table-row')){const repetitions=repeat(row,'number-rows-repeated');if(rowCount+repetitions>512)truncated=true;for(let r=0;r<Math.min(repetitions,512-rowCount);r++){const tr=document.createElement('tr');let columns=0;for(const cell of row.children){if(cell.namespaceURI!==NS.table||!['table-cell','covered-table-cell'].includes(cell.localName))continue;const count=repeat(cell,'number-columns-repeated');if(columns+count>128)truncated=true;for(let c=0;c<Math.min(count,128-columns);c++){if(++cells>30000)throw Error('ODF exceeds 30000 visible cells');const td=document.createElement('td');const paras=cell.getElementsByTagNameNS(NS.text,'p');if(paras.length)for(const p of paras)paragraph(p,td);else td.textContent=attr(cell,'office','value')||attr(cell,'office','date-value')||attr(cell,'office','boolean-value')||attr(cell,'office','string-value')||'';tr.append(td);}columns+=Math.min(count,128-columns);if(columns===128)break;}grid.append(tr);}rowCount+=Math.min(repetitions,512-rowCount);if(rowCount===512)break;}target.append(heading,grid);if(truncated){const p=document.createElement('p');p.textContent='Table preview truncated at 512 rows or 128 columns.';target.append(p);}};
 const blocks=(node,target,depth=0)=>{if(depth>64)throw Error('ODF block nesting exceeds 64');for(const child of node.children){if(child.namespaceURI===NS.table&&child.localName==='table')table(child,target);else if(child.namespaceURI===NS.text&&['p','h'].includes(child.localName))paragraph(child,target);else if(child.namespaceURI!==NS.office||child.localName!=='scripts')blocks(child,target,depth+1);}};
 if(family==='presentation'){const pages=content.getElementsByTagNameNS(NS.draw,'page');if(pages.length>100)throw Error('ODF exceeds 100 slides');for(const [index,page] of [...pages].entries()){const section=document.createElement('section');section.className='odf-slide';const title=document.createElement('h2');title.textContent=attr(page,'draw','name')||'Slide '+(index+1);section.append(title);blocks(page,section);host.append(section);}}else blocks(content,host);
 return host;
}
