// SPDX-License-Identifier: GPL-3.0-only
// Bounded JS port of Allegro 16.4 binary record layouts/length rules from
// bernayigit/brd_parser revision f38fb8f48031eb78d654a78a79453e580b634f93.
import layout from './layout.json' with {type:'json'};
export function readDra(source){const b=new Uint8Array(source),d=new DataView(b.buffer,b.byteOffset,b.byteLength);if(b.length<0x1200||b.length>32*1024*1024||d.getUint32(0,true)!==0x00130c03)throw Error('DRA reader requires native Allegro 16.4 signature');let p=0x1200;const bound=(o,n)=>{if(!Number.isSafeInteger(o)||!Number.isSafeInteger(n)||o<0||n<0||o+n>b.length)throw Error('Truncated Allegro native record');},u16=o=>{bound(o,2);return d.getUint16(o,true);},u32=o=>{bound(o,4);return d.getUint32(o,true);},aligned=n=>Math.ceil(n/4)*4,strings=[],ids=new Set(),decode=(o,n)=>new TextDecoder('windows-1252').decode(b.subarray(o,o+n));const count=u32(layout['header.strings_count']);if(count>10000)throw Error('Allegro string count limit');for(let i=0;i<count;i++){const id=u32(p);p+=4;let end=p;while(end<b.length&&b[end]!==0&&end-p<=65536)end++;if(end===b.length||end-p>65536||ids.has(id))throw Error('Invalid Allegro string record');ids.add(id);strings.push({id,text:decode(p,end-p)});const n=aligned(end-p+1);bound(p,n);p+=n;}
 const records=[],segments=[],counts={},layers=[];while(p<b.length&&b[p]!==0){if(records.length>=100000)throw Error('Allegro record count limit');const start=p,t=b[p],key='0x'+t.toString(16).padStart(2,'0');let n=layout[key];let info={};if(t===3){bound(p,16);const subtype=b[p+12],size=u16(p+14);n=16;if(subtype===0x65){}else if([0x64,0x66,0x67,0x6a].includes(subtype))n+=4;else if([0x6d,0x6e,0x6f,0x68,0x6b,0x71,0x73,0x78].includes(subtype))n+=aligned(size);else if(subtype===0x69)n+=8;else if(subtype===0x6c)n+=4+u32(p+16)*4;else if([0x70,0x74].includes(subtype))n+=4+u16(p+18)+4*u16(p+16);else if(subtype===0xf6)n+=80;else throw Error('Unsupported Allegro attribute subtype '+subtype);info={attributeSubtype:subtype};}
 else if(t===0x1c)n=layout.x1C+(10+b[p+layout['x1C<A_164>.layer_count']]*3)*layout.t13+u16(p+2)*32;
 else if(t===0x1d)n=layout.x1D+u16(p+20)*256+u16(p+22)*56;
 else if(t===0x1e)n=layout.x1E_hdr+aligned(u32(p+20));
 else if(t===0x1f)n=layout.x1F+u16(p+26)*280+4;
 else if(t===0x21){const subtype=u16(p+2);n=subtype===1304?layout.stackup_material:subtype===0x0407?20+1028:u32(p+4);if(n<12)throw Error('Invalid Allegro native metadata size');info={metadataSubtype:subtype};}
 else if(t===0x27){const end=u32(layout['header.x27_end_offset'])-1;if(end<=p)throw Error('Invalid Allegro native opaque-record boundary');n=end-p;}
 else if(t===0x29){n=56;bound(p,n);info={pinCoordinates:[d.getInt32(p+24,true),d.getInt32(p+28,true)],padstackReference:u32(p+32)};}
 else if(t===0x2a){const count=u16(p+2);if(count>256)throw Error('Allegro layer count limit');n=4+36*count+4;bound(p,n);const entries=[];for(let i=0;i<count;i++){const offset=p+4+i*36;let end=offset;while(end<offset+32&&b[end]!==0)end++;entries.push({name:decode(offset,end-offset),flags:[...b.subarray(offset+32,offset+36)]});}layers.push({id:u32(p+n-4),entries});}
 else if(t===0x31)n=layout.x31+aligned(u16(p+22));
 else if(t===0x35)n=124;
 else if(t===0x36){const subtype=u16(p+2),count=u32(p+12),sizes={2:layout.x36_x02,3:layout.x36_x03,6:layout.x36_x06,8:layout.x36_x08,5:28,11:1016,12:232,13:200,15:layout['x36_x0F<A_164>'],16:108};if(!sizes[subtype])throw Error('Unsupported Allegro native table subtype '+subtype);n=layout.x36+count*sizes[subtype];info={tableSubtype:subtype,tableCount:count};}
 else if(t===0x3b)n=layout.x3B+aligned(u32(p+4));
 else if(t===0x3c)n=layout.x3C+4*u32(p+8);
 if(!n||n<4)throw Error('Unsupported Allegro record '+key+' at '+p);bound(p,n);const id=n>=8?u32(p+4):null;records.push({type:key,id,offset:p,bytes:n,...info});counts[key]=(counts[key]||0)+1;
 if([0x15,0x16,0x17].includes(t)){if(segments.length>=10000)throw Error('Allegro segment count limit');const coordinates=Array.from({length:4},(_,i)=>d.getInt32(p+24+i*4,true));segments.push({type:key,id,parent:u32(p+12),width:u32(p+20),coordinates});}p+=n;if(p<=start)throw Error('Invalid Allegro native record progress');}
 const pins=records.filter(r=>r.type==='0x29').map(r=>({id:r.id,coordinates:r.pinCoordinates,padstackReference:r.padstackReference}));if(!records.length||(!segments.length&&!pins.length))throw Error('DRA profile found no native geometry');const versionOffset=layout['header.allegro_version'];let versionEnd=versionOffset;while(versionEnd<versionOffset+60&&b[versionEnd]!==0)versionEnd++;return{nativeVersion:'16.4',versionString:decode(versionOffset,versionEnd-versionOffset),stringCount:count,strings,layers,recordCount:records.length,counts,segments,pins,nativeRecords:records.slice(0,1000),recordPreviewTruncated:records.length>1000,remainingOpaqueBytes:b.length-p,headerObjectCount:u32(layout['header.object_count'])};}
