"""Original native Sony LRF fixture generated by Mike Higgins' MIT writer."""
import io,sys,json,base64
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent/'native-lrf-writer'))
from pylrf import LrfWriter,LrfObject,LrfTag,LrfTagStream
def fixture(metadata=None):
    w=LrfWriter('utf-8');w.docInfoXml=metadata if metadata is not None else '<Info><BookInfo><Title>Original42</Title><Author>Native Writer</Author></BookInfo></Info>'
    root=LrfObject('BookAtr',1);root.append(LrfTag('ChildPageTree',2));tree=LrfObject('PageTree',2);tree.append(LrfTag('PageList',[3]));page=LrfObject('Page',3);block=LrfObject('Block',4);text=LrfObject('TextBlock',5)
    for obj,target in [(page,4),(block,5)]:obj.appendLrfTags(LrfTagStream(0,[LrfTag('Link',target)]).getStreamTags('utf-8'))
    text.appendLrfTags(LrfTagStream(0x100,[LrfTag('pstart',0),LrfTag('rawtext','Original42 <script>window.userExecuted=1</script> '),LrfTag('Italic'),LrfTag('rawtext','Native italic'),LrfTag('ItalicEnd'),LrfTag('CR'),LrfTag('rawtext','Second line'),LrfTag('pend')]).getStreamTags('utf-8'))
    w.setRootObject(root);w.setPageTreeId(2);w.objects=[root,tree,page,block,text];
    out=io.BytesIO();w.writeFile(out);return out.getvalue()
if __name__=="__main__":print(json.dumps({"lrf":base64.b64encode(fixture()).decode()}))
