const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {once}=require('node:events');const express=require('express');const {chromium}=require('playwright');const {fixtures}=require('./adobe-fixtures');const root=path.resolve(__dirname,'..');
async function main(){
 const samples=await require('./odf-fixtures').fixtures();
 const app=express(),requests=[];let blockWorker=false,blockedResolve,blockedResponse;app.use((req,res,next)=>{requests.push(req.path);if(blockWorker&&req.path.endsWith('/upstream-viewer/bridge.js')){blockedResponse=res;blockedResolve();return;}next();});app.get('/project/test',(_,res)=>res.send(`<div id="host" style="height:650px;width:1200px"></div><script>window.ace={config:{set(){},setModuleUrl(){}},require(){return{}},define(){}};const add=document.addEventListener.bind(document);document.addEventListener=(e,...a)=>{if(e!=='DOMContentLoaded')add(e,...a)};const NativeWorker=Worker;window.activeWorkers=new Set();window.Worker=class extends NativeWorker{constructor(...a){super(...a);activeWorkers.add(this);}terminate(){activeWorkers.delete(this);return super.terminate();}};window.createdUrls=new Set();const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=create(b);createdUrls.add(u);return u;};URL.revokeObjectURL=u=>{createdUrls.delete(u);revoke(u);};</script><script src="/project/bundle.js"></script>`));app.use('/project',express.static(path.join(root,'public')));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage(),errors=[],external=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser:',e.message);});page.on('request',r=>{if(!/^(http:\/\/127\.0\.0\.1:|blob:|data:)/.test(r.url()))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/project/test`);assert(!requests.some(p=>/viewer-chunks|upstream-viewer/.test(p)));await page.evaluate(()=>{window.plugin=__gleViewerRequire('shared:src/plugins.js').getPlugins().find(p=>p.id==='upstream-readers');window.openUpstream=async(name,bytes)=>{window.events={};plugin.init({projectFiles:{f:{id:'f',name,bytes:new Uint8Array(bytes)}}});window.panel=new plugin.components.upstreamViewer({element:document.getElementById('host'),on:(e,fn)=>(events[e]||=[]).push(fn)},{fileId:'f'});await panel.ready;};window.closeUpstream=()=>events.destroy.forEach(fn=>fn());});
 for(const [ext,bytes] of Object.entries(samples)){
  await page.evaluate(({name,bytes})=>openUpstream(name,bytes),{name:'sample.'+ext,bytes:[...bytes]});
  assert.equal(await page.evaluate(()=>panel.model.typeId),'odf');const shell=page.frameLocator('.upstream-reader-frame');await shell.locator('.odf-table').waitFor();assert.deepEqual(await shell.locator('.odf-table tr:first-child td').allTextContents(),['Original42','42','42']);assert.equal(await shell.locator('.odf-table tr').count(),3);assert.equal(await page.evaluate(()=>window.hacked),undefined);if(ext!=='fods'){assert((await shell.locator('.odf-document').innerText()).includes('<script>parent.hacked=1</script>'));assert.equal(await shell.locator('span[style*="bold"]').innerText(),'Bold42');}if(['odp','fodp'].includes(ext))assert((await shell.locator('.odf-slide h2').innerText()).includes('Slide42'));
  assert.equal(await page.evaluate(()=>activeWorkers.size),0);await page.evaluate(()=>closeUpstream());assert.equal(await page.evaluate(()=>createdUrls.size),0);console.log(ext+': preview/structure, text safety and disposal passed');
 }
 await assert.rejects(page.evaluate(()=>openUpstream('bad.odt',[1,2,3,4])),/ZIP/i);await page.evaluate(()=>closeUpstream());await assert.rejects(page.evaluate(()=>openUpstream('bad.fodt',[...new TextEncoder().encode('<office:document/>')])),/XML|ODF/i);await page.evaluate(()=>closeUpstream());await assert.rejects(page.evaluate(bytes=>openUpstream('mismatch.odp',bytes),[...samples.odt]),/mimetype/i);await page.evaluate(()=>closeUpstream());
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(requests.filter(p=>/viewer-chunks\/upstream-plugin/.test(p)).length,1);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
