const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {once}=require('node:events');const express=require('express');const {chromium}=require('playwright');const {fixtures}=require('./adobe-fixtures');const root=path.resolve(__dirname,'..');
async function main(){
 const bytes=require('./layout-fixtures').fixture();const samples={gds:bytes,gdsii:bytes};
 const app=express(),requests=[];let blockWorker=false,blockedResolve,blockedResponse;app.use((req,res,next)=>{requests.push(req.path);if(blockWorker&&req.path.endsWith('/layout-viewer/worker.js')){blockedResponse=res;blockedResolve();return;}next();});app.get('/project/test',(_,res)=>res.send(`<div id="host" style="height:650px;width:1200px"></div><script>window.ace={config:{set(){},setModuleUrl(){}},require(){return{}},define(){}};const add=document.addEventListener.bind(document);document.addEventListener=(e,...a)=>{if(e!=='DOMContentLoaded')add(e,...a)};const NativeWorker=Worker;window.activeWorkers=new Set();window.Worker=class extends NativeWorker{constructor(...a){super(...a);activeWorkers.add(this);}terminate(){activeWorkers.delete(this);return super.terminate();}};window.createdUrls=new Set();const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=create(b);createdUrls.add(u);return u;};URL.revokeObjectURL=u=>{createdUrls.delete(u);revoke(u);};</script><script src="/project/bundle.js"></script>`));app.use('/project',express.static(path.join(root,'public')));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!/^(http:\/\/127\.0\.0\.1:|blob:|data:)/.test(r.url()))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/project/test`);assert(!requests.some(p=>/viewer-chunks|layout-viewer/.test(p)));await page.evaluate(()=>{window.plugin=__gleViewerRequire('shared:src/plugins.js').getPlugins().find(p=>p.id==='layout');window.openLayout=async(name,bytes)=>{window.events={};plugin.init({projectFiles:{f:{id:'f',name,bytes:new Uint8Array(bytes)}}});window.panel=new plugin.components.layoutViewer({element:document.getElementById('host'),on:(e,fn)=>(events[e]||=[]).push(fn)},{fileId:'f'});await panel.ready;};window.closeLayout=()=>events.destroy.forEach(fn=>fn());});
 for(const [ext,bytes] of Object.entries(samples)){
  await page.evaluate(({name,bytes})=>openLayout(name,bytes),{name:'sample.'+ext,bytes:[...bytes]});
  assert.equal(await page.locator('.gds-layout polygon').getAttribute('points'),'0,0 100,0 100,-100 0,-100 0,0');assert.equal(await page.locator('.gds-layout polyline').getAttribute('points'),'10,-10 90,-90');assert.equal(await page.locator('.gds-layout text').textContent(),'<script>safe</script>');assert.equal(await page.locator('.gds-layout script').count(),0);
  const viewBox=await page.locator('.gds-layout').getAttribute('viewBox');await page.getByRole('button',{name:'+',exact:true}).click();assert.notEqual(await page.locator('.gds-layout').getAttribute('viewBox'),viewBox);await page.getByLabel('Layout cell').selectOption('CELL');assert.equal(await page.locator('.gds-layout polygon').count(),1);await page.getByRole('button',{name:'Reset',exact:true}).click();assert.equal(await page.locator('.gds-layout').getAttribute('viewBox'),viewBox);
  const model=await page.evaluate(()=>panel.model);assert.equal(model.elements.length,3);assert.deepEqual(model.bounds,{minX:0,minY:0,maxX:100,maxY:100});
  assert.equal(await page.evaluate(()=>activeWorkers.size),0);await page.evaluate(()=>closeLayout());assert.equal(await page.evaluate(()=>createdUrls.size),0);console.log(ext+': preview/structure, text safety and disposal passed');
 }
 blockWorker=true;const blocked=new Promise(resolve=>blockedResolve=resolve);const opening=page.evaluate(bytes=>openLayout('closing.gds',bytes),[...samples.gds]);await blocked;await page.evaluate(()=>closeLayout());await opening;assert.equal(await page.evaluate(()=>activeWorkers.size),0);blockedResponse.end();blockWorker=false;
 await assert.rejects(page.evaluate(()=>openLayout('bad.gds',[0,1,2])),/GDSII HEADER/i);await page.evaluate(()=>closeLayout());assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(requests.filter(p=>/viewer-chunks\/layout-plugin/.test(p)).length,1);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
