const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {once}=require('node:events');const express=require('express');const {chromium}=require('playwright');const {fixtures}=require('./adobe-fixtures');const root=path.resolve(__dirname,'..');
async function main(){
 const samples=require('./azw3-fixtures').fixtures();if(process.env.TEST_AZW3_FILE)samples['real.azw3']=fs.readFileSync(process.env.TEST_AZW3_FILE);
 const app=express(),requests=[];let blockWorker=false,blockedResolve,blockedResponse;app.use((req,res,next)=>{requests.push(req.path);if(blockWorker&&req.path.endsWith('/azw3-viewer/worker.js')){blockedResponse=res;blockedResolve();return;}next();});app.get('/project/test',(_,res)=>res.send(`<div id="host" style="height:650px;width:1200px"></div><script>window.ace={config:{set(){},setModuleUrl(){}},require(){return{}},define(){}};const add=document.addEventListener.bind(document);document.addEventListener=(e,...a)=>{if(e!=='DOMContentLoaded')add(e,...a)};const NativeWorker=Worker;window.activeWorkers=new Set();window.Worker=class extends NativeWorker{constructor(...a){super(...a);activeWorkers.add(this);}terminate(){activeWorkers.delete(this);return super.terminate();}};window.createdUrls=new Set();const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=create(b);createdUrls.add(u);return u;};URL.revokeObjectURL=u=>{createdUrls.delete(u);revoke(u);};</script><script src="/project/bundle.js"></script>`));if(process.env.TEST_FOLIATE_SOURCE)app.get('/oracle/mobi.js',(_,res)=>res.sendFile(path.join(process.env.TEST_FOLIATE_SOURCE,'mobi.js')));app.use('/project',express.static(path.join(root,'public')));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage(),errors=[],external=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser:',e.message);});page.on('request',r=>{if(!/^(http:\/\/127\.0\.0\.1:|blob:|data:)/.test(r.url()))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/project/test`);assert(!requests.some(p=>/viewer-chunks|upstream-viewer/.test(p)));await page.evaluate(()=>{window.plugin=__gleViewerRequire('shared:src/plugins.js').getPlugins().find(p=>p.id==='upstream-readers');window.openUpstream=async(name,bytes)=>{window.events={};plugin.init({projectFiles:{f:{id:'f',name,bytes:new Uint8Array(bytes)}}});window.panel=new plugin.components.upstreamViewer({element:document.getElementById('host'),on:(e,fn)=>(events[e]||=[]).push(fn)},{fileId:'f'});await panel.ready;};window.closeUpstream=()=>events.destroy.forEach(fn=>fn());});
 for(const [ext,bytes] of Object.entries(samples)){
  await page.evaluate(({name,base64})=>openUpstream(name,Uint8Array.from(atob(base64),c=>c.charCodeAt(0))),{name:'sample.'+ext,base64:bytes.toString('base64')});
  assert.equal(await page.evaluate(()=>panel.model.typeId),'azw3');const shell=page.frameLocator('.upstream-reader-frame'),host=shell.locator('.azw3-native');await host.waitFor();const model=JSON.parse(await host.locator('.azw3-metadata').textContent());assert.equal(model.version,8);assert.equal(model.title,ext==='real.azw3'?'Pride and Prejudice':'Original42');assert.equal(model.sectionCount,ext==='real.azw3'?76:1);assert.equal(await host.locator('.azw3-section').count(),model.sectionCount);if(ext!=='real.azw3'){assert.equal(await host.locator('em').textContent(),'Native fragment');assert((await host.locator('.azw3-section').textContent()).includes('<script>window.userExecuted=1</script>'));if(process.env.TEST_FOLIATE_SOURCE){const oracle=await page.evaluate(async bytes=>{const {MOBI}=await import('/oracle/mobi.js');const book=await new MOBI({unzlib:()=>{throw Error('Fixture does not need zlib');}}).open(new File([new Uint8Array(bytes)],'native.azw3'));const doc=await book.sections[0].createDocument();const result={title:book.metadata.title,text:doc.querySelector('body').textContent};book.destroy();return result;},[...bytes]);assert.equal(oracle.title,'Original42');assert(oracle.text.includes('Native fragment'));}}else{assert.equal(model.fragmentCount,167);assert.deepEqual(model.creators,['Jane Austen']);assert(/it is a truth universally acknowledged/i.test((await host.locator('.azw3-section').allTextContents()).join('').replace(/\s+/g,' ')));}assert.equal(await host.locator('script,img,iframe').count(),0);assert.equal(await shell.locator('body').evaluate(()=>window.userExecuted),undefined);
  assert.equal(page.workers().length,0);assert.equal(await page.evaluate(()=>activeWorkers.size),0);await page.evaluate(()=>closeUpstream());assert.equal(await page.evaluate(()=>createdUrls.size),0);console.log(ext+': preview/structure, text safety and disposal passed');
 }
 blockWorker=true;const blocked=new Promise(resolve=>blockedResolve=resolve);const opening=page.evaluate(bytes=>openUpstream('closing.azw3',bytes),[...samples.azw3]);await blocked;await page.evaluate(()=>closeUpstream());await opening;assert.equal(page.workers().length,0);assert.equal(await page.evaluate(()=>createdUrls.size),0);blockedResponse.end();blockWorker=false;
 await assert.rejects(page.evaluate(bytes=>openUpstream('bad.azw3',bytes),[1,2,3]),/native bounds/);await page.evaluate(()=>closeUpstream());const offset=samples.azw3.readUInt32BE(78),wrong=Buffer.from(samples.azw3);wrong.writeUInt32BE(6,offset+36);await assert.rejects(page.evaluate(bytes=>openUpstream('mobi6.azw3',bytes),[...wrong]),/pure native KF8/);await page.evaluate(()=>closeUpstream());const encrypted=Buffer.from(samples.azw3);encrypted.writeUInt16BE(2,offset+12);await assert.rejects(page.evaluate(bytes=>openUpstream('encrypted.azw3',bytes),[...encrypted]),/Encrypted/);await page.evaluate(()=>closeUpstream());const broken=Buffer.from(samples.azw3);broken.writeUInt32BE(99999,offset+252);await assert.rejects(page.evaluate(bytes=>openUpstream('broken-index.azw3',bytes),[...broken]),/record reference/);await page.evaluate(()=>closeUpstream());assert.equal(page.workers().length,0);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(requests.filter(p=>/viewer-chunks\/upstream-plugin/.test(p)).length,1);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
