const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {once}=require('node:events');const express=require('express');const {chromium}=require('playwright');const {fixtures}=require('./adobe-fixtures');const root=path.resolve(__dirname,'..');
async function main(){
 const samples=require('./ofc-fixtures').fixtures();
 const app=express(),requests=[];let blockWorker=false,blockedResolve,blockedResponse;app.use((req,res,next)=>{requests.push(req.path);if(blockWorker&&req.path.endsWith('/upstream-viewer/bridge.js')){blockedResponse=res;blockedResolve();return;}next();});app.get('/project/test',(_,res)=>res.send(`<div id="host" style="height:650px;width:1200px"></div><script>window.ace={config:{set(){},setModuleUrl(){}},require(){return{}},define(){}};const add=document.addEventListener.bind(document);document.addEventListener=(e,...a)=>{if(e!=='DOMContentLoaded')add(e,...a)};const NativeWorker=Worker;window.activeWorkers=new Set();window.Worker=class extends NativeWorker{constructor(...a){super(...a);activeWorkers.add(this);}terminate(){activeWorkers.delete(this);return super.terminate();}};window.createdUrls=new Set();const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=create(b);createdUrls.add(u);return u;};URL.revokeObjectURL=u=>{createdUrls.delete(u);revoke(u);};</script><script src="/project/bundle.js"></script>`));app.use('/project',express.static(path.join(root,'public')));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage(),errors=[],external=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser:',e.message);});page.on('request',r=>{if(!/^(http:\/\/127\.0\.0\.1:|blob:|data:)/.test(r.url()))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/project/test`);assert(!requests.some(p=>/viewer-chunks|upstream-viewer/.test(p)));await page.evaluate(()=>{window.plugin=__gleViewerRequire('shared:src/plugins.js').getPlugins().find(p=>p.id==='upstream-readers');window.openUpstream=async(name,bytes)=>{window.events={};plugin.init({projectFiles:{f:{id:'f',name,bytes:new Uint8Array(bytes)}}});window.panel=new plugin.components.upstreamViewer({element:document.getElementById('host'),on:(e,fn)=>(events[e]||=[]).push(fn)},{fileId:'f'});await panel.ready;};window.closeUpstream=()=>events.destroy.forEach(fn=>fn());});
 for(const [ext,bytes] of Object.entries(samples)){
  await page.evaluate(({name,bytes})=>openUpstream(name,bytes),{name:'sample.'+ext,bytes:[...bytes]});
  assert.equal(await page.evaluate(()=>panel.model.typeId),'ofc');const shell=page.frameLocator('.upstream-reader-frame'),host=shell.locator('.ofc-native');await host.waitFor();const rows=await host.locator('table tr').allTextContents();assert.equal(rows.length,3);assert(rows[1].includes('2024-01-02 12:34:56'));assert(rows[1].includes('-42.00'));assert(rows[1].includes('Crédit42'));assert(rows[1].includes('<script>parent.hacked=1</script>'));assert(rows[2].includes('42.00Original42credit42'));assert((await host.locator('h2').textContent()).includes('****5642'));assert(!(await host.innerText()).includes('12345642'));assert((await host.screenshot()).length>1000);assert.equal(await host.locator('script,img,iframe').count(),0);assert.equal(await page.evaluate(()=>window.hacked),undefined);
  assert.equal(page.workers().length,0);assert.equal(await page.evaluate(()=>activeWorkers.size),0);await page.evaluate(()=>closeUpstream());assert.equal(await page.evaluate(()=>createdUrls.size),0);console.log(ext+': preview/structure, text safety and disposal passed');
 }
 const source=require('./ofc-fixtures').sample(65001);for(const [bad,re]of [[source.replace('20240102123456','20240231123456'),/calendar date/],[source.replace('-42,00','-42.0'),/decimal amount/],[source.replace('</STMTRS>','</ACCTSTMT>'),/Mismatched/],[source.replace('65001','9999'),/CPAGE/]]){await assert.rejects(page.evaluate(bytes=>openUpstream('bad.ofc',bytes),[...Buffer.from(bad)]),re);await page.evaluate(()=>closeUpstream());}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(requests.filter(p=>/viewer-chunks\/upstream-plugin/.test(p)).length,1);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
