const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {once}=require('node:events');const express=require('express');const {chromium}=require('playwright');const {fixtures}=require('./adobe-fixtures');const root=path.resolve(__dirname,'..');
async function main(){
 const samples={};for(const ext of ['pages','numbers'])samples['legacy.'+ext]=fs.readFileSync(path.join(__dirname,'fixtures/iwork/legacy.'+ext));
 const authored=await require('./iwork-fixtures').fixtures();samples['legacy.key']=authored.key;samples['modern.pages']=authored.pages;
 if(process.env.TEST_IWORK_FIXTURE_DIR)for(const [kind,ext] of [['pages','pages'],['numbers','numbers'],['keynote','key']])for(const filename of fs.readdirSync(path.join(process.env.TEST_IWORK_FIXTURE_DIR,kind)).filter(name=>/^libetonyek-|^current-/.test(name)))samples[filename]=fs.readFileSync(path.join(process.env.TEST_IWORK_FIXTURE_DIR,kind,filename));
 const app=express(),requests=[];let blockWorker=false,blockedResolve,blockedResponse;app.use((req,res,next)=>{requests.push(req.path);if(blockWorker&&req.path.endsWith('/iwork-viewer/worker.js')){blockedResponse=res;blockedResolve();return;}next();});app.get('/project/test',(_,res)=>res.send(`<div id="host" style="height:650px;width:1200px"></div><script>window.ace={config:{set(){},setModuleUrl(){}},require(){return{}},define(){}};const add=document.addEventListener.bind(document);document.addEventListener=(e,...a)=>{if(e!=='DOMContentLoaded')add(e,...a)};const NativeWorker=Worker;window.activeWorkers=new Set();window.Worker=class extends NativeWorker{constructor(...a){super(...a);activeWorkers.add(this);}terminate(){activeWorkers.delete(this);return super.terminate();}};window.createdUrls=new Set();const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=create(b);createdUrls.add(u);return u;};URL.revokeObjectURL=u=>{createdUrls.delete(u);revoke(u);};</script><script src="/project/bundle.js"></script>`));app.use('/project',express.static(path.join(root,'public')));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!/^(http:\/\/127\.0\.0\.1:|blob:|data:)/.test(r.url()))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/project/test`);assert(!requests.some(p=>/viewer-chunks|iwork-viewer/.test(p)));await page.evaluate(()=>{window.plugin=__gleViewerRequire('shared:src/plugins.js').getPlugins().find(p=>p.id==='iwork');window.openIwork=async(name,bytes)=>{window.events={};plugin.init({projectFiles:{f:{id:'f',name,bytes:new Uint8Array(bytes)}}});window.panel=new plugin.components.iworkViewer({element:document.getElementById('host'),on:(e,fn)=>(events[e]||=[]).push(fn)},{fileId:'f'});await panel.ready;};window.closeIwork=()=>events.destroy.forEach(fn=>fn());});
 for(const [ext,bytes] of Object.entries(samples)){
  await page.evaluate(({name,bytes})=>openIwork(name,bytes),{name:'sample.'+ext,bytes:[...bytes]});
  assert(await page.locator('.iwork-scene').count()>0);if(/^(legacy|current)/.test(ext))assert((await page.locator('.iwork-scene').allTextContents()).join('').length>0,ext+' visible scene text');
  if(ext==='legacy.numbers')assert.match((await page.locator('.iwork-scene').allTextContents()).join(''),/Saved total.*42/s);else if(ext==='legacy.pages')assert.match((await page.locator('.iwork-scene').allTextContents()).join(''),/iWork 09/);
  if(ext.startsWith('current-')){const model=await page.evaluate(()=>panel.model);assert.equal(model.limitedPreview,false);assert.equal(model.scenes.length,2);const marker=ext.includes('pages')?'PAGES-CURRENT-15-3-1':ext.includes('numbers')?'NUMBERS-CURRENT-15-3-1':'KEYNOTE-CURRENT-15-3-1';assert.match(JSON.stringify(model.scenes),new RegExp(marker));}
  if(ext.endsWith('.numbers'))assert(await page.locator('.iwork-scene table').count()>0);
  const scale=await page.locator('.iwork-scene-wrap').first().evaluate(el=>el.style.cssText);await page.getByRole('button',{name:'+',exact:true}).click();assert.notEqual(await page.locator('.iwork-scene-wrap').first().evaluate(el=>el.style.cssText),scale);
  assert.equal(await page.evaluate(()=>activeWorkers.size),0);await page.evaluate(()=>closeIwork());assert.equal(await page.evaluate(()=>createdUrls.size),0);console.log(ext+': preview/structure, text safety and disposal passed');
 }
 await page.evaluate(bytes=>openIwork('sample.pages',bytes),[...samples['legacy.pages']]);await page.locator('input[type=file]').setInputFiles({name:'picked.numbers',mimeType:'application/octet-stream',buffer:samples['legacy.numbers']});await page.waitForFunction(()=>document.querySelector('#host').textContent.includes('picked.numbers · 1 scenes'));assert(await page.locator('.iwork-scene table').count()>0);await page.evaluate(()=>closeIwork());
 await page.evaluate(()=>{const {isIworkFile:check}=__gleViewerRequire('shared:src/lazy-viewers.js').getLoadedModule('iwork-plugin');if(check({name:'private.key',content:'-----BEGIN PRIVATE KEY-----'}))throw Error('Key collision');if(!check({name:'deck.key',bytes:new TextEncoder().encode('PK')}))throw Error('Keynote signature');});
 blockWorker=true;const blocked=new Promise(resolve=>blockedResolve=resolve);const opening=page.evaluate(bytes=>openIwork('closing.pages',bytes),[...samples['legacy.pages']]);await blocked;await page.evaluate(()=>closeIwork());await opening;assert.equal(await page.evaluate(()=>activeWorkers.size),0);blockedResponse.end();blockWorker=false;
 await assert.rejects(page.evaluate(bytes=>openIwork('strings-only.pages',bytes),[...fs.readFileSync(path.join(__dirname,'fixtures/iwork/strings-only.pages'))]),/native iWork scene|ArchiveInfo|Snappy|IWA|illegal/i);await page.evaluate(()=>closeIwork());
 await assert.rejects(page.evaluate(()=>openIwork('bad.pages',[0,1,2])),/zip|central|corrupt|end of data/i);await page.evaluate(()=>closeIwork());assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(requests.filter(p=>/viewer-chunks\/iwork-plugin/.test(p)).length,1);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
