const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {once}=require('node:events');const express=require('express');const {chromium}=require('playwright');const {fixtures}=require('./adobe-fixtures');const root=path.resolve(__dirname,'..');
async function main(){
 const samples=await require('./ofd-fixtures').fixtures();
 const app=express(),requests=[];let blockWorker=false,blockedResolve,blockedResponse;app.use((req,res,next)=>{requests.push(req.path);if(blockWorker&&req.path.endsWith('/upstream-viewer/bridge.js')){blockedResponse=res;blockedResolve();return;}next();});app.get('/project/test',(_,res)=>res.send(`<div id="host" style="height:650px;width:1200px"></div><script>window.ace={config:{set(){},setModuleUrl(){}},require(){return{}},define(){}};const add=document.addEventListener.bind(document);document.addEventListener=(e,...a)=>{if(e!=='DOMContentLoaded')add(e,...a)};const NativeWorker=Worker;window.activeWorkers=new Set();window.Worker=class extends NativeWorker{constructor(...a){super(...a);activeWorkers.add(this);}terminate(){activeWorkers.delete(this);return super.terminate();}};window.createdUrls=new Set();const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=create(b);createdUrls.add(u);return u;};URL.revokeObjectURL=u=>{createdUrls.delete(u);revoke(u);};</script><script src="/project/bundle.js"></script>`));app.use('/project',express.static(path.join(root,'public')));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage(),errors=[],external=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser:',e.message);});page.on('request',r=>{if(!/^(http:\/\/127\.0\.0\.1:|blob:|data:)/.test(r.url()))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/project/test`);assert(!requests.some(p=>/viewer-chunks|upstream-viewer/.test(p)));await page.evaluate(()=>{window.plugin=__gleViewerRequire('shared:src/plugins.js').getPlugins().find(p=>p.id==='upstream-readers');window.openUpstream=async(name,bytes)=>{window.events={};plugin.init({projectFiles:{f:{id:'f',name,bytes:new Uint8Array(bytes)}}});window.panel=new plugin.components.upstreamViewer({element:document.getElementById('host'),on:(e,fn)=>(events[e]||=[]).push(fn)},{fileId:'f'});await panel.ready;};window.closeUpstream=()=>events.destroy.forEach(fn=>fn());});
 for(const [ext,bytes] of Object.entries(samples)){
  await page.evaluate(({name,bytes})=>openUpstream(name,bytes),{name:'sample.'+ext,bytes:[...bytes]});
  assert.equal(await page.evaluate(()=>panel.model.typeId),'ofd');const shell=page.frameLocator('.upstream-reader-frame'),host=shell.locator('.ofd-native'),drawing=host.locator('.ofd-page');await drawing.waitFor();assert((await host.innerText()).includes('210 × 297 mm'));assert.equal(await drawing.getAttribute('viewBox'),'0 0 210 297');assert.equal(await drawing.locator('path').getAttribute('d'),'M0 0 L40 0 L40 20 L0 20 Z ');assert.equal(await drawing.locator('path').locator('..').getAttribute('transform'),'translate(42 24)');assert.equal(await drawing.locator('text').nth(9).getAttribute('x'),'36');assert.equal((await drawing.locator('text').allTextContents()).join(''),'Original42<script>parent.hacked=1</script>');const {PNG}=require('pngjs');const img=PNG.sync.read(await drawing.screenshot());let red=0;for(let i=0;i<img.data.length;i+=4)if(img.data[i]>245&&img.data[i+1]<5&&img.data[i+2]<5)red++;assert(red>500);assert.equal(await host.locator('script,img,iframe').count(),0);assert.equal(await page.evaluate(()=>window.hacked),undefined);
  assert.equal(page.workers().length,0);assert.equal(await page.evaluate(()=>activeWorkers.size),0);await page.evaluate(()=>closeUpstream());assert.equal(await page.evaluate(()=>createdUrls.size),0);console.log(ext+': preview/structure, text safety and disposal passed');
 }
 await assert.rejects(page.evaluate(()=>openUpstream('bad.ofd',[1,2,3,4])),/ZIP|container/);await page.evaluate(()=>closeUpstream());const zip=await require('jszip').loadAsync(samples.ofd);zip.file('Doc_0/Document.xml','<bad/>');const bad=await zip.generateAsync({type:'nodebuffer'});await assert.rejects(page.evaluate(bytes=>openUpstream('bad.ofd',bytes),[...bad]),/Document root/);await page.evaluate(()=>closeUpstream());
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(requests.filter(p=>/viewer-chunks\/upstream-plugin/.test(p)).length,1);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
