const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {once}=require('node:events');const express=require('express');const {chromium}=require('playwright');const {fixtures}=require('./adobe-fixtures');const root=path.resolve(__dirname,'..');
async function main(){
 const samples=require('./dra-fixtures').fixtures();if(process.env.TEST_DRA_SOURCE)for(const name of ['0201','0402r_old'])samples[name+'.dra']=fs.readFileSync(path.join(process.env.TEST_DRA_SOURCE,name+'.dra'));
 const app=express(),requests=[];let blockWorker=false,blockedResolve,blockedResponse;app.use((req,res,next)=>{requests.push(req.path);if(blockWorker&&req.path.endsWith('/dra-viewer/worker.js')){blockedResponse=res;blockedResolve();return;}next();});app.get('/project/test',(_,res)=>res.send(`<div id="host" style="height:650px;width:1200px"></div><script>window.ace={config:{set(){},setModuleUrl(){}},require(){return{}},define(){}};const add=document.addEventListener.bind(document);document.addEventListener=(e,...a)=>{if(e!=='DOMContentLoaded')add(e,...a)};const NativeWorker=Worker;window.activeWorkers=new Set();window.Worker=class extends NativeWorker{constructor(...a){super(...a);activeWorkers.add(this);}terminate(){activeWorkers.delete(this);return super.terminate();}};window.createdUrls=new Set();const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=b=>{const u=create(b);createdUrls.add(u);return u;};URL.revokeObjectURL=u=>{createdUrls.delete(u);revoke(u);};</script><script src="/project/bundle.js"></script>`));app.use('/project',express.static(path.join(root,'public')));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({executablePath:process.env.TEST_CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage(),errors=[],external=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser:',e.message);});page.on('request',r=>{if(!/^(http:\/\/127\.0\.0\.1:|blob:|data:)/.test(r.url()))external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/project/test`);assert(!requests.some(p=>/viewer-chunks|upstream-viewer/.test(p)));await page.evaluate(()=>{window.plugin=__gleViewerRequire('shared:src/plugins.js').getPlugins().find(p=>p.id==='upstream-readers');window.openUpstream=async(name,bytes)=>{window.events={};plugin.init({projectFiles:{f:{id:'f',name,bytes:new Uint8Array(bytes)}}});window.panel=new plugin.components.upstreamViewer({element:document.getElementById('host'),on:(e,fn)=>(events[e]||=[]).push(fn)},{fileId:'f'});await panel.ready;};window.closeUpstream=()=>events.destroy.forEach(fn=>fn());});
 for(const [ext,bytes] of Object.entries(samples)){
  await page.evaluate(({name,bytes})=>openUpstream(name,bytes),{name:'sample.'+ext,bytes:[...bytes]});
  assert.equal(await page.evaluate(()=>panel.model.typeId),'dra');const shell=page.frameLocator('.upstream-reader-frame'),host=shell.locator('.dra-native'),drawing=host.locator('.dra-projection');await drawing.waitFor();const model=JSON.parse(await host.locator('.dra-metadata').textContent());assert.equal(model.nativeVersion,'16.4');const points=ext==='dra'?[[60,42]]:ext==='0201.dra'?[[1968,0],[-2032,0]]:[[-1673,0],[1673,0]];assert.deepEqual(model.pins.map(p=>p.coordinates),points);assert.equal(await drawing.locator('circle').count(),points.length);assert.equal(await drawing.locator('line').count(),ext==='dra'?1:ext==='0201.dra'?0:6);if(ext==='dra'){assert.deepEqual(model.segments[0].coordinates,[42,24,80,24]);assert.equal(model.strings[0].text,'<script>window.userExecuted=1</script>');assert.equal(model.recordCount,2);}assert((await drawing.screenshot()).length>1000);assert.equal(await host.locator('script,img,iframe').count(),0);assert.equal(await shell.locator('body').evaluate(()=>window.userExecuted),undefined);
  assert.equal(page.workers().length,0);assert.equal(await page.evaluate(()=>activeWorkers.size),0);await page.evaluate(()=>closeUpstream());assert.equal(await page.evaluate(()=>createdUrls.size),0);console.log(ext+': preview/structure, text safety and disposal passed');
 }
 blockWorker=true;const blocked=new Promise(resolve=>blockedResolve=resolve);const opening=page.evaluate(bytes=>openUpstream('closing.dra',bytes),[...samples.dra]);await blocked;await page.evaluate(()=>closeUpstream());await opening;assert.equal(page.workers().length,0);assert.equal(await page.evaluate(()=>createdUrls.size),0);blockedResponse.end();blockWorker=false;
 for(const bytes of [Buffer.from([1,2,3]),samples.dra.subarray(0,samples.dra.length-3)]){await assert.rejects(page.evaluate(bytes=>openUpstream('bad.dra',bytes),[...bytes]),/signature|Truncated/);await page.evaluate(()=>closeUpstream());}const broken=Buffer.from(samples.dra);const pos=0x1200+4+Math.ceil(Buffer.byteLength('<script>window.userExecuted=1</script>\0')/4)*4;broken[pos]=0x18;await assert.rejects(page.evaluate(bytes=>openUpstream('unknown-record.dra',bytes),[...broken]),/Unsupported Allegro record/);await page.evaluate(()=>closeUpstream());assert.equal(page.workers().length,0);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(requests.filter(p=>/viewer-chunks\/upstream-plugin/.test(p)).length,1);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
