use parasolid_core::{BuiltinProfileRegistry,DocumentLimits,InspectionLimits,SchemaKey,RawNode,inspect_xt,inspect_xb,parse_xt,parse_xb};
use parasolid_core::brep::{BrepModel,CurveKind,map_xt_brep_with_diagnostic_limit,map_xb_brep_with_diagnostic_limit};
use serde_json::{json,Value};
use std::collections::{BTreeMap,BTreeSet};
fn result(bytes:&[u8],kind:u32)->Result<Value,String>{
 let limits=DocumentLimits{max_file_size:8*1024*1024,max_nodes:5000,max_schema_types:4096,max_fields_per_type:128,max_string_bytes:65536,max_variable_elements:10000};let inspection=InspectionLimits{max_file_size:limits.max_file_size,max_string_bytes:limits.max_string_bytes};
 let key_string=if kind==0{inspect_xt(bytes,inspection).map_err(|e|e.to_string())?.schema_key}else{inspect_xb(bytes,inspection).map_err(|e|e.to_string())?.schema_key};let key=SchemaKey::parse(&key_string).map_err(|e|e.to_string())?;let registry=BuiltinProfileRegistry::compiled().map_err(|e|e.to_string())?;let provider=registry.provider_for_key(&key).ok_or_else(||format!("Unsupported exact Parasolid schema key: {key_string}"))?;
 if kind==0{let doc=parse_xt(bytes,&provider,limits).map_err(|e|e.to_string())?;let model=map_xt_brep_with_diagnostic_limit(&doc,500).map_err(|e|e.to_string())?;Ok(summary(&key_string,&doc.nodes,&model))}else{let doc=parse_xb(bytes,&provider,limits).map_err(|e|e.to_string())?;let model=map_xb_brep_with_diagnostic_limit(&doc,500).map_err(|e|e.to_string())?;Ok(summary(&key_string,&doc.nodes,&model))}
}
fn summary(key:&str,nodes:&[RawNode],model:&BrepModel)->Value{
 let mut counts=BTreeMap::<u16,usize>::new();for node in nodes{*counts.entry(node.node_type).or_default()+=1;}
 let points=model.points.iter().map(|p|json!({"id":p.id,"coordinates":[p.position.x,p.position.y,p.position.z]})).collect::<Vec<_>>();let point_by_id=model.points.iter().map(|p|(p.id,[p.position.x,p.position.y,p.position.z])).collect::<BTreeMap<_,_>>();let vertices=model.vertices.iter().map(|v|(v.id,v.point)).collect::<BTreeMap<_,_>>();let lines=model.curves.iter().filter_map(|c|if matches!(c.kind,CurveKind::Line{..}){Some(c.id)}else{None}).collect::<BTreeSet<_>>();let mut edges=Vec::new();for e in &model.edges{if !e.curve.is_some_and(|c|lines.contains(&c)){continue;}if let (Some(a),Some(b))=(e.start_vertex,e.end_vertex){if let (Some(a),Some(b))=(vertices.get(&a).and_then(|p|point_by_id.get(p)),vertices.get(&b).and_then(|p|point_by_id.get(p))){edges.push(json!([a,b]));}}}
 let raw=nodes.iter().take(100).map(|n|json!({"index":n.index,"nodeType":n.node_type,"byteRange":[n.byte_range.start,n.byte_range.end],"fields":n.fields.iter().map(|f|json!({"name":f.definition.name,"codec":format!("{:?}",f.definition.field_type),"count":f.values.len(),"firstValues":f.values.iter().take(10).map(|v|format!("{v:?}")).collect::<Vec<_>>()})).collect::<Vec<_>>()})).collect::<Vec<_>>();
 json!({"schemaKey":key,"nodeCount":nodes.len(),"counts":counts,"complete":model.complete,"bodies":model.bodies.len(),"faces":model.faces.len(),"vertices":model.vertices.len(),"points":points,"straightEdges":edges,"diagnostics":model.diagnostics.iter().map(|d|format!("{d:?}")).collect::<Vec<_>>(),"nativeNodes":raw,"nodePreviewTruncated":nodes.len()>100})
}
#[unsafe(no_mangle)]pub extern "C" fn allocate(length:u32)->u32{if length>8*1024*1024{return 0;}let b=vec![0u8;length as usize].into_boxed_slice();Box::into_raw(b) as *mut u8 as u32}
// Buffers are created by this module, used once by one dedicated worker, and
// returned with their original length. No caller-provided arbitrary pointers.
#[unsafe(no_mangle)]pub unsafe extern "C" fn release(pointer:u32,length:u32){unsafe{drop(Box::from_raw(std::ptr::slice_from_raw_parts_mut(pointer as *mut u8,length as usize)));}}
#[unsafe(no_mangle)]pub unsafe extern "C" fn decode(pointer:u32,length:u32,kind:u32)->u64{let data=unsafe{std::slice::from_raw_parts(pointer as *const u8,length as usize)};let value=if length>8*1024*1024||kind>1{json!({"error":"Invalid Parasolid input limits/kind"})}else{match result(data,kind){Ok(v)=>v,Err(e)=>json!({"error":e})}};let mut output=value.to_string().into_bytes();if output.len()>8*1024*1024{output=b"{\"error\":\"Parasolid preview exceeds 8 MiB\"}".to_vec();}let output=output.into_boxed_slice();let length=output.len() as u64;let pointer=Box::into_raw(output) as *mut u8 as u64;(length<<32)|pointer}
