const {registerPlugin}=require('./plugins');const {ImportedViewerPanel,element,details,card}=require('./imported-viewer-panel');const {readWorker}=require('./worker-reader');let ctx;
class LayoutPanel extends ImportedViewerPanel{
 constructor(container,state){const active={controller:new AbortController()};container.on('destroy',()=>active.controller.abort());super(container,state,ctx,{accept:'.gds,.gdsii',parse:bytes=>readWorker('layout-viewer/worker.js',{bytes},active.controller.signal),render(model,host,bar){
  const notes=card(host,model.libraryName||'GDSII layout');details(notes,'Cells',model.structures.join(', '));details(notes,'Database unit',String(model.databaseUnit||'Unspecified'));for(const note of model.warnings)details(notes,'Reader note',note);
  const select=element('select',undefined,bar);select.setAttribute('aria-label','Layout cell');for(const name of ['All cells',...model.structures]){const option=element('option',name,select);option.value=name;}
  const canvas=document.createElementNS('http://www.w3.org/2000/svg','svg');canvas.classList.add('gds-layout');canvas.style.cssText='width:100%;height:550px;background:#111';canvas.setAttribute('role','img');canvas.setAttribute('aria-label','GDSII geometry');host.append(canvas);let scale=1;
  const b=model.bounds||{minX:0,minY:0,maxX:100,maxY:100},width=Math.max(1,b.maxX-b.minX),height=Math.max(1,b.maxY-b.minY),span=Math.max(width,height),pad=span*.05;
  const node=(tag,attrs,text)=>{const e=document.createElementNS(canvas.namespaceURI,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;canvas.append(e);return e;};
  const draw=()=>{canvas.replaceChildren();const w=(width+pad*2)/scale,h=(height+pad*2)/scale;canvas.setAttribute('viewBox',`${b.minX+width/2-w/2} ${-b.maxY+height/2-h/2} ${w} ${h}`);for(const shape of model.elements){if(select.value!=='All cells'&&shape.structure!==select.value)continue;const color=['#6fd3ed','#f8be67','#e6a2ed','#99e38c'][Math.abs(shape.layer||0)%4],points=shape.xy.map(p=>`${p.x},${-p.y}`).join(' ');if(shape.kind==='boundary')node('polygon',{points,fill:color,'fill-opacity':.5,stroke:color,'stroke-width':span/500});else if(shape.kind==='path')node('polyline',{points,fill:'none',stroke:color,'stroke-width':shape.width||span/500});else if(shape.kind==='text')node('text',{x:shape.xy[0].x,y:-shape.xy[0].y,fill:color,'font-size':span/30},shape.text);else{node('circle',{cx:shape.xy[0].x,cy:-shape.xy[0].y,r:span/100,fill:color});node('text',{x:shape.xy[0].x,y:-shape.xy[0].y,fill:color,'font-size':span/30},'Ref '+shape.reference+' (not expanded)');}}};select.onchange=draw;draw();
  const buttons=[];for(const [label,factor] of [['−',.8],['+',1.25],['Reset',0]]){const button=element('button',label,bar);button.onclick=()=>{scale=factor?Math.max(.1,Math.min(20,scale*factor)):1;draw();};buttons.push(button);}return{destroy(){select.remove();buttons.forEach(b=>b.remove());canvas.remove();}};
 }});this.active=active;}
 async show(bytes,name){this.active.controller.abort();this.active.controller=new AbortController();this.options.parse=bytes=>readWorker('layout-viewer/worker.js',{bytes,name},this.active.controller.signal);return super.show(bytes,name);}
}
registerPlugin({id:'layout',name:'GDSII layouts',components:{layoutViewer:LayoutPanel},toolbarButtons:[{label:'GDSII layout',title:'Open GDSII mask layout',menuLabel:'GDSII layouts'}],init(context){ctx=context;}});
