const {registerPlugin}=require('./plugins');const {resolveAssetUrl}=require('./lazy-viewers');const {readBytes,element}=require('./imported-viewer-panel');let ctx;
class UpstreamPanel{
 constructor(container,state){this.root=container.element;this.sequence=0;this.destroyed=false;this.root.style.cssText='height:100%;display:flex;flex-direction:column;background:#20242a;color:#eee';const bar=element('div',undefined,this.root);bar.style.cssText='display:flex;gap:8px;padding:8px';const open=element('button','Open',bar);this.input=element('input',undefined,bar);this.input.type='file';this.input.accept='.ait,.psdt,.pdd,.jfif,.pjpe,.pjpeg,.xla,.xlam,.xlt,.xltm,.xltx,.eot,.vhd,.hex,.webarchive,.xhtml,.lrc,.m3u8,.sig,.odt,.odp,.fodt,.fodp,.fods,.umd,.mermaid,.mmd,.typst,.markdown,.mdown,.mkd,.txt,.text,.lot,.tab,.ans,.nfo,.diz,.gc,.svgz,.abc,.als,.prproj,.h2song,.h2pattern,.h2drumkit,.kicad_pro,.kicad_prl,.kicad_mod,.kicad_sym,.kicad_wks,.kicad_dru,.pem,.crt,.cer,.der,.nii,.shp,.wad,.bsp,.dmp,.mdmp,.crash,.ips,.acf,.p7m,.p7s,.p7b,.p7c,.pkcs7,.cms,.cmsc,.tsd,.tst,.tsq,.tsr,.asics,.scs,.asice,.sce,.ers,.jws,.srt,.vtt,.diff,.patch,.gitignore,.dockerignore,.npmignore,.eslintignore,.prettierignore,.hgignore,.ssh-config,.proto,.thrift,.reg,.rdp,.kube,.kubeconfig,.har,.sarif,.geojson,.topojson,.kml,.mt,.mt940,.mt942,.sta,.ofx,.qfx,.qif,.rtf,.dockerfile,.url,.webloc,.cif,.cif2,.mmcif,.pdb,.ent,.mol,.sd,.sdf,.bcf,.db3,.s3db,.sl3,.gpkg,.mbtiles,.fa,.fasta,.fna,.faa,.ffn,.frn,.fsa,.mpfa,.fq,.fastq,.bed,.gff,.gff3,.gff2,.gtf,.hl7,.hl7v2,.msh,.ini,.cfg,.conf,.properties,.env,.toml,.yaml,.yml,.jsonc,.json5,.jsonl,.ndjson,.ldjson,.xsd,.xsl,.xslt,.wsdl,.pom,.csproj,.props,.targets,.resx,.rss,.atom,.plist,.stringsdict,.strings,.mobi,.azw,.eml,.mbox,.msg,.mmp,.mmpz,.ppt,.pot,.pps,.bson,.cbor,.msgpack,.mpk,.f3d,.f3z,.sketch,.procreate,.mat,.dbf,.exe,.dll,.dylib,.macho,.class,.pyc,.pyo,.lnk,.torrent';this.input.hidden=true;open.onclick=()=>this.input.click();this.label=element('span','Choose a file',bar);this.frame=element('iframe',undefined,this.root);this.frame.className='upstream-reader-frame';this.frame.title='File preview';this.frame.style.cssText='width:100%;flex:1;min-height:0;border:0';this.frame.setAttribute('sandbox','allow-scripts allow-same-origin');this.resetRuntime();
  this.listener=event=>{if(event.source!==this.frame.contentWindow||event.origin!==location.origin||!event.data?.readerBridge||event.data.nonce!==this.nonce)return;if(event.data.ready){clearTimeout(this.loadTimer);this.loadError=null;this.finishLoad();return;}if(event.data.id!==this.sequence)return;if(event.data.error){this.label.textContent=event.data.error;this.pending?.reject(Error(event.data.error));}else{this.model=event.data.model;this.label.textContent=this.name+' · '+this.model.summary;this.pending?.resolve(this.model);}this.pending=null;};window.addEventListener('message',this.listener);
  this.input.onchange=async()=>{const f=this.input.files[0];if(f)await this.show(new Uint8Array(await f.arrayBuffer()),f.name);};container.on('destroy',()=>this.destroy());this.ready=this.init(state||{});
 }
 resetRuntime(){clearTimeout(this.loadTimer);this.nonce=crypto.randomUUID();this.loadError=null;this.loaded=new Promise(resolve=>{this.finishLoad=resolve;});this.loadTimer=setTimeout(()=>{this.loadError='Reader runtime failed to initialize in 15 seconds';this.finishLoad();},15000);const url=new URL(resolveAssetUrl('upstream-viewer/bridge.html'));url.searchParams.set('nonce',this.nonce);this.frame.src=url.href;}
 async init(state){if(!state.fileId)return;const file=ctx.projectFiles[state.fileId];if(!file)throw Error('Missing file '+state.fileId);await this.show(await readBytes(file,ctx),file.name);}
 async show(bytes,name){if(this.destroyed)return;if(bytes.byteLength>64*1024*1024)throw Error('Reader input exceeds 64 MiB');const id=++this.sequence;this.pending?.resolve({cancelled:true});this.name=name;this.label.textContent=name+' · reading…';await this.loaded;if(this.destroyed||id!==this.sequence)return;if(this.loadError){this.label.textContent=this.loadError;throw Error(this.loadError);}return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending=null;this.resetRuntime();reject(Error('Reader exceeded 60 seconds'));},60000);this.pending={resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}};const copy=bytes.slice();this.frame.contentWindow.postMessage({readerBridge:true,nonce:this.nonce,id,name,bytes:copy},location.origin,[copy.buffer]);});}
 destroy(){if(this.destroyed)return;this.destroyed=true;++this.sequence;this.pending?.resolve({cancelled:true});this.pending=null;clearTimeout(this.loadTimer);this.finishLoad();window.removeEventListener('message',this.listener);this.frame.remove();this.root.replaceChildren();}
}
registerPlugin({id:'upstream-readers',name:'Imported readers',components:{upstreamViewer:UpstreamPanel},toolbarButtons:[{label:'Imported reader',title:'Open a structured binary file',menuLabel:'Imported reader'}],init(context){ctx=context;}});
